#ifndef __NOTIFYPACKETDEF_H__
#define __NOTIFYPACKETDEF_H__

#include <NotifyPacket.h>
#include <NotifyGUIDs.h>

#define DEFINE_NOTIFY_PACKET(name, guid)  \
class name : public CNotify               \
{                                         \
public:                                   \
   name() : CNotify(guid) { }             \
};

DEFINE_NOTIFY_PACKET(   EPSTARTREAD,         STARTREADGUID           )
DEFINE_NOTIFY_PACKET(   EPENDPAGE,           ENDPAGEGUID             )
DEFINE_NOTIFY_PACKET(   STOP,                STOPGUID                )
DEFINE_NOTIFY_PACKET(   STARTSEGMENT,        STARTSEGMENTGUID        )
DEFINE_NOTIFY_PACKET(   STARTMONITOR,        STARTMONITORGUID        )
DEFINE_NOTIFY_PACKET(   STARTIMPTEST,        STARTIMPTESTGUID        )
DEFINE_NOTIFY_PACKET(   PHOTICNOTIFY,        PHOTICNOTIFYGUID        )
DEFINE_NOTIFY_PACKET(   HVNOTIFY,            HVNOTIFYGUID            )
DEFINE_NOTIFY_PACKET(   DERIVATIONCHANGED,   DERIVATIONCHANGEDGUID   )
DEFINE_NOTIFY_PACKET(   STARTFFT,            STARTFFTGUID            )
DEFINE_NOTIFY_PACKET(   STOPFFT,             STOPFFTGUID             )
DEFINE_NOTIFY_PACKET(   PLAYDIRNOTIFY,       PLAYDIRGUID             )
DEFINE_NOTIFY_PACKET(   ALARMRESET,          ALARMRESETGUID          )
DEFINE_NOTIFY_PACKET(   RTSNOTIFY,           RTSNOTIFYGUID           )
DEFINE_NOTIFY_PACKET(   OVERFLOWNOTIFY,      OVERFLOWNOTIFYGUID      )
DEFINE_NOTIFY_PACKET(   DETECTIONCOMPLETED,  DETECTIONCOMPLETEDGUID  )
DEFINE_NOTIFY_PACKET(   TRENDGENCOMPLETED,   TRENDGENCOMPLETEDGUID   )
DEFINE_NOTIFY_PACKET(   STARTSPLIT,          STARTSPLITGUID          )
DEFINE_NOTIFY_PACKET(   STOPSPLIT,           STOPSPLITGUID           )
DEFINE_NOTIFY_PACKET(   FILESTARTED,         FILESTARTEDGUID         )
DEFINE_NOTIFY_PACKET(   FILESTOPPED,         FILESTOPPEDGUID         )
DEFINE_NOTIFY_PACKET(   PROTOCOLCHANGED,     PROTOCOLCHANGEDGUID     )
DEFINE_NOTIFY_PACKET(   PROTOCOLCHANGING,    PROTOCOLCHANGINGGUID    )
DEFINE_NOTIFY_PACKET(   SLEEPSCORESCHANGED,  SLEEPSCORECHANGEDGUID   )
DEFINE_NOTIFY_PACKET(   PAGESECONDSNOTIFY,   PAGESECONDSGUID         )
DEFINE_NOTIFY_PACKET(   PLAYSPEEDNOTIFY,     PLAYSPEEDGUID           )
DEFINE_NOTIFY_PACKET(   CANCELALARM,         CANCELALARMGUID         )
DEFINE_NOTIFY_PACKET(   REMAININGTIMELOCAL,  REMAININGTIMELOCALGUID  )
DEFINE_NOTIFY_PACKET(   REMAININGTIMESERVER, REMAININGTIMESERVERGUID )
DEFINE_NOTIFY_PACKET(   REMAININGSTATELOCAL, REMAININGSTATELOCALGUID )
DEFINE_NOTIFY_PACKET(   REMAININGSTATESERVER, REMAININGSTATESERVERGUID )
DEFINE_NOTIFY_PACKET(   UPDATETIMECURSOR,     UPDATETIMECURSORGUID    )
DEFINE_NOTIFY_PACKET(   SOFTWARECALIBRATION, SOFTWARECALIBRATIONGUID )
DEFINE_NOTIFY_PACKET(   CORTSTIMNOTIFY,      CORTSTIMNOTIFYGUID      )
DEFINE_NOTIFY_PACKET(   LOGITNOTIFY,         LOGITGUID               )
DEFINE_NOTIFY_PACKET(   STARTTRENDS,         STARTTRENDSGUID         )
DEFINE_NOTIFY_PACKET(   TRENDSFINISHED,      TRENDSFINISHEDGUID      )
DEFINE_NOTIFY_PACKET(   CAMERACONTROLCHANGE, CAMERACONTROLCHANGEGUID )
DEFINE_NOTIFY_PACKET(   CAMERAPRESETCHANGE,  CAMERAPRESETCHANGEGUID  )
DEFINE_NOTIFY_PACKET(   VIDEOTYPE_MEDIAPORT, MEDIAPORTGUID )
DEFINE_NOTIFY_PACKET(   VIDEOTYPE_WINNOV,    WINNOVGUID )
DEFINE_NOTIFY_PACKET(   MEDIAPORTVIDEOFILESPLIT,    MEDIAPORTVIDEOFILESPLITGUID )
DEFINE_NOTIFY_PACKET(	MEDIAPORTVIDEOTIMEOUT,		MEDIAPORTVIDEOTIMEOUTGUID	)
DEFINE_NOTIFY_PACKET(	VIDEORECORDING,		VIDEORECORDINGGUID	)
#endif //__NOTIFYPACKETDEF_H__
