// Import declarations for include/BAlert.h, generated by dylib_imports.sh
#ifndef BAlert_IMPORTS_H
#define BAlert_IMPORTS_H

#include "Win32Defs.h"

#define BAlertGetDeviceType BAlertGetDeviceType_bc8e
#define BAlertStart BAlertStart_5a1b
#define BAlertStop BAlertStop_1020
#define BAlertWaitForData BAlertWaitForData_a9d2

#include "BAlert.h"

#undef BAlertGetDeviceType
#undef BAlertStart
#undef BAlertStop
#undef BAlertWaitForData

extern "C" {
extern int (__stdcall *BAlertGetDeviceType)();
extern int (__stdcall *BAlertStart)(bool bUseFilter);
extern int (__stdcall *BAlertStop)();
extern int (__stdcall *BAlertWaitForData)(float* fBuffer, int nBlockSize);
}

namespace Dylib { bool BAlert_Loaded(); }

#endif // BAlert_IMPORTS_H
