// Import declarations for EnobioDLL.h, generated by dylib_imports.sh
#ifndef EnobioDLL_IMPORTS_H
#define EnobioDLL_IMPORTS_H

#include "Win32Defs.h"

#if DYNAMIC_IMPORTS
#define CEnobioCreate CEnobioCreate_c2d5
#define CEnobioInitialize CEnobioInitialize_6d54
#define CEnobioCaptureStart CEnobioCaptureStart_b03a
#define CEnobioWaitForData CEnobioWaitForData_ad8d
#define CEnobioCaptureStop CEnobioCaptureStop_9c46
#define CEnobioClose CEnobioClose_28c2
#define CEnobioGetLastError CEnobioGetLastError_a870
#define CEnobioStrError CEnobioStrError_0894
#define CEnobioIsInitialized CEnobioIsInitialized_2877
#define CEnobioChannelStatus CEnobioChannelStatus_5991
#define CEnobioResetBuffer CEnobioResetBuffer_80ab
#endif // DYNAMIC_IMPORTS

#include "EnobioDLL.h"

#if DYNAMIC_IMPORTS
#undef CEnobioCreate
#undef CEnobioInitialize
#undef CEnobioCaptureStart
#undef CEnobioWaitForData
#undef CEnobioCaptureStop
#undef CEnobioClose
#undef CEnobioGetLastError
#undef CEnobioStrError
#undef CEnobioIsInitialized
#undef CEnobioChannelStatus
#undef CEnobioResetBuffer

extern "C" {
extern Enobio* (__cdecl *CEnobioCreate)();
extern bool (__cdecl *CEnobioInitialize)(Enobio* enobioClass,int sampleBlockSize);
extern bool (__cdecl *CEnobioCaptureStart) (Enobio* enobioClass) ;
extern bool (__cdecl *CEnobioWaitForData)(Enobio* enobioClass,int** buf,int sampleBlockSize);
extern bool (__cdecl *CEnobioCaptureStop) (Enobio* enobioClass);
extern bool (__cdecl *CEnobioClose)(Enobio* enobioClass);
extern int (__cdecl *CEnobioGetLastError)(Enobio* enobioClass);
extern const char * (__cdecl *CEnobioStrError)(int NumError,Enobio* enobioClass);
extern bool (__cdecl *CEnobioIsInitialized)(Enobio* enobioClass);
extern int* (__cdecl *CEnobioChannelStatus)(Enobio*);
extern void (__cdecl *CEnobioResetBuffer)(Enobio* enobioClass);
}
#endif // DYNAMIC_IMPORTS

namespace Dylib { bool EnobioDLL_Loaded(); }

#endif // EnobioDLL_IMPORTS_H
