// Import definitions for tobii_research library
// generated Tue Aug 08 16:05:50 2017 by DylibTool
#ifndef TOBII_RESEARCH_IMPORTS_H
#define TOBII_RESEARCH_IMPORTS_H

#include "Win32Defs.h"

#ifndef STATIC_LIBTOBII_RESEARCH
// Disable function declarations in the original header
// file by #defining function names to point to symbols that
// are not referenced by any code.
#define tobii_research_find_all_eyetrackers __77555307_tobii_research_find_all_eyetrackers
#define tobii_research_free_eyetrackers __0d323e58_tobii_research_free_eyetrackers
#define tobii_research_get_eyetracker __024f6e6b_tobii_research_get_eyetracker
#define tobii_research_get_sdk_version __063e5d75_tobii_research_get_sdk_version
#define tobii_research_get_system_time_stamp __65614365_tobii_research_get_system_time_stamp
#define tobii_research_logging_subscribe __0b36070e_tobii_research_logging_subscribe
#define tobii_research_logging_unsubscribe __73481105_tobii_research_logging_unsubscribe
#define tobii_research_subscribe_to_external_signal_data __17273404_tobii_research_subscribe_to_external_signal_data
#define tobii_research_subscribe_to_eye_image __3c56546c_tobii_research_subscribe_to_eye_image
#define tobii_research_subscribe_to_eye_image_as_gif __636e5c79_tobii_research_subscribe_to_eye_image_as_gif
#define tobii_research_subscribe_to_gaze_data __0c474b45_tobii_research_subscribe_to_gaze_data
#define tobii_research_subscribe_to_hmd_gaze_data __642a2f1a_tobii_research_subscribe_to_hmd_gaze_data
#define tobii_research_subscribe_to_notifications __5a2d2832_tobii_research_subscribe_to_notifications
#define tobii_research_subscribe_to_stream_errors __46291226_tobii_research_subscribe_to_stream_errors
#define tobii_research_subscribe_to_time_synchronization_data __3954424b_tobii_research_subscribe_to_time_synchronization_data
#define tobii_research_unsubscribe_from_external_signal_data __42427f69_tobii_research_unsubscribe_from_external_signal_data
#define tobii_research_unsubscribe_from_eye_image __69331f01_tobii_research_unsubscribe_from_eye_image
#define tobii_research_unsubscribe_from_eye_image_as_gif __360b1714_tobii_research_unsubscribe_from_eye_image_as_gif
#define tobii_research_unsubscribe_from_gaze_data __59220028_tobii_research_unsubscribe_from_gaze_data
#define tobii_research_unsubscribe_from_hmd_gaze_data __314f6477_tobii_research_unsubscribe_from_hmd_gaze_data
#define tobii_research_unsubscribe_from_notifications __0f48635f_tobii_research_unsubscribe_from_notifications
#define tobii_research_unsubscribe_from_stream_errors __134c594b_tobii_research_unsubscribe_from_stream_errors
#define tobii_research_unsubscribe_from_time_synchronization_data __6c310926_tobii_research_unsubscribe_from_time_synchronization_data
#define tobii_research_apply_calibration_data __01415f71_tobii_research_apply_calibration_data
#define tobii_research_apply_licenses __344f5860_tobii_research_apply_licenses
#define tobii_research_clear_applied_licenses __1b52407d_tobii_research_clear_applied_licenses
#define tobii_research_free_calibration_data __73455c64_tobii_research_free_calibration_data
#define tobii_research_free_eye_tracking_modes __3f244e78_tobii_research_free_eye_tracking_modes
#define tobii_research_free_gaze_output_frequencies __4d51481b_tobii_research_free_gaze_output_frequencies
#define tobii_research_free_string __624b392e_tobii_research_free_string
#define tobii_research_get_address __7f5e031d_tobii_research_get_address
#define tobii_research_get_all_eye_tracking_modes __78201138_tobii_research_get_all_eye_tracking_modes
#define tobii_research_get_all_gaze_output_frequencies __0d26724a_tobii_research_get_all_gaze_output_frequencies
#define tobii_research_get_capabilities __09300a6c_tobii_research_get_capabilities
#define tobii_research_get_device_name __0505767f_tobii_research_get_device_name
#define tobii_research_get_display_area __12263f70_tobii_research_get_display_area
#define tobii_research_get_eye_tracking_mode __674c4e59_tobii_research_get_eye_tracking_mode
#define tobii_research_get_firmware_version __7f436524_tobii_research_get_firmware_version
#define tobii_research_get_gaze_output_frequency __04392d3b_tobii_research_get_gaze_output_frequency
#define tobii_research_get_hmd_lens_configuration __653f2f39_tobii_research_get_hmd_lens_configuration
#define tobii_research_get_model __072d1418_tobii_research_get_model
#define tobii_research_get_serial_number __0c06130c_tobii_research_get_serial_number
#define tobii_research_get_track_box __454a7d7e_tobii_research_get_track_box
#define tobii_research_retrieve_calibration_data __01222e19_tobii_research_retrieve_calibration_data
#define tobii_research_set_device_name __0505766b_tobii_research_set_device_name
#define tobii_research_set_eye_tracking_mode __674c4e4d_tobii_research_set_eye_tracking_mode
#define tobii_research_set_gaze_output_frequency __04392d2f_tobii_research_set_gaze_output_frequency
#define tobii_research_set_hmd_lens_configuration __653f2f2d_tobii_research_set_hmd_lens_configuration

#define __declspec(x)
#endif // STATIC_LIBTOBII_RESEARCH

#include "tobii_research.h"
#include "tobii_research_streams.h"
#include "tobii_research_eyetracker.h"

#ifndef STATIC_LIBTOBII_RESEARCH
#undef __declspec
// Use #undef to restore function names before declaring
// function pointers with the names originally used to
// declare imports.
#undef tobii_research_find_all_eyetrackers
extern decltype(&__77555307_tobii_research_find_all_eyetrackers) tobii_research_find_all_eyetrackers;
#undef tobii_research_free_eyetrackers
extern decltype(&__0d323e58_tobii_research_free_eyetrackers) tobii_research_free_eyetrackers;
#undef tobii_research_get_eyetracker
extern decltype(&__024f6e6b_tobii_research_get_eyetracker) tobii_research_get_eyetracker;
#undef tobii_research_get_sdk_version
extern decltype(&__063e5d75_tobii_research_get_sdk_version) tobii_research_get_sdk_version;
#undef tobii_research_get_system_time_stamp
extern decltype(&__65614365_tobii_research_get_system_time_stamp) tobii_research_get_system_time_stamp;
#undef tobii_research_logging_subscribe
extern decltype(&__0b36070e_tobii_research_logging_subscribe) tobii_research_logging_subscribe;
#undef tobii_research_logging_unsubscribe
extern decltype(&__73481105_tobii_research_logging_unsubscribe) tobii_research_logging_unsubscribe;
#undef tobii_research_subscribe_to_external_signal_data
extern decltype(&__17273404_tobii_research_subscribe_to_external_signal_data) tobii_research_subscribe_to_external_signal_data;
#undef tobii_research_subscribe_to_eye_image
extern decltype(&__3c56546c_tobii_research_subscribe_to_eye_image) tobii_research_subscribe_to_eye_image;
#undef tobii_research_subscribe_to_eye_image_as_gif
extern decltype(&__636e5c79_tobii_research_subscribe_to_eye_image_as_gif) tobii_research_subscribe_to_eye_image_as_gif;
#undef tobii_research_subscribe_to_gaze_data
extern decltype(&__0c474b45_tobii_research_subscribe_to_gaze_data) tobii_research_subscribe_to_gaze_data;
#undef tobii_research_subscribe_to_hmd_gaze_data
extern decltype(&__642a2f1a_tobii_research_subscribe_to_hmd_gaze_data) tobii_research_subscribe_to_hmd_gaze_data;
#undef tobii_research_subscribe_to_notifications
extern decltype(&__5a2d2832_tobii_research_subscribe_to_notifications) tobii_research_subscribe_to_notifications;
#undef tobii_research_subscribe_to_stream_errors
extern decltype(&__46291226_tobii_research_subscribe_to_stream_errors) tobii_research_subscribe_to_stream_errors;
#undef tobii_research_subscribe_to_time_synchronization_data
extern decltype(&__3954424b_tobii_research_subscribe_to_time_synchronization_data) tobii_research_subscribe_to_time_synchronization_data;
#undef tobii_research_unsubscribe_from_external_signal_data
extern decltype(&__42427f69_tobii_research_unsubscribe_from_external_signal_data) tobii_research_unsubscribe_from_external_signal_data;
#undef tobii_research_unsubscribe_from_eye_image
extern decltype(&__69331f01_tobii_research_unsubscribe_from_eye_image) tobii_research_unsubscribe_from_eye_image;
#undef tobii_research_unsubscribe_from_eye_image_as_gif
extern decltype(&__360b1714_tobii_research_unsubscribe_from_eye_image_as_gif) tobii_research_unsubscribe_from_eye_image_as_gif;
#undef tobii_research_unsubscribe_from_gaze_data
extern decltype(&__59220028_tobii_research_unsubscribe_from_gaze_data) tobii_research_unsubscribe_from_gaze_data;
#undef tobii_research_unsubscribe_from_hmd_gaze_data
extern decltype(&__314f6477_tobii_research_unsubscribe_from_hmd_gaze_data) tobii_research_unsubscribe_from_hmd_gaze_data;
#undef tobii_research_unsubscribe_from_notifications
extern decltype(&__0f48635f_tobii_research_unsubscribe_from_notifications) tobii_research_unsubscribe_from_notifications;
#undef tobii_research_unsubscribe_from_stream_errors
extern decltype(&__134c594b_tobii_research_unsubscribe_from_stream_errors) tobii_research_unsubscribe_from_stream_errors;
#undef tobii_research_unsubscribe_from_time_synchronization_data
extern decltype(&__6c310926_tobii_research_unsubscribe_from_time_synchronization_data) tobii_research_unsubscribe_from_time_synchronization_data;
#undef tobii_research_apply_calibration_data
extern decltype(&__01415f71_tobii_research_apply_calibration_data) tobii_research_apply_calibration_data;
#undef tobii_research_apply_licenses
extern decltype(&__344f5860_tobii_research_apply_licenses) tobii_research_apply_licenses;
#undef tobii_research_clear_applied_licenses
extern decltype(&__1b52407d_tobii_research_clear_applied_licenses) tobii_research_clear_applied_licenses;
#undef tobii_research_free_calibration_data
extern decltype(&__73455c64_tobii_research_free_calibration_data) tobii_research_free_calibration_data;
#undef tobii_research_free_eye_tracking_modes
extern decltype(&__3f244e78_tobii_research_free_eye_tracking_modes) tobii_research_free_eye_tracking_modes;
#undef tobii_research_free_gaze_output_frequencies
extern decltype(&__4d51481b_tobii_research_free_gaze_output_frequencies) tobii_research_free_gaze_output_frequencies;
#undef tobii_research_free_string
extern decltype(&__624b392e_tobii_research_free_string) tobii_research_free_string;
#undef tobii_research_get_address
extern decltype(&__7f5e031d_tobii_research_get_address) tobii_research_get_address;
#undef tobii_research_get_all_eye_tracking_modes
extern decltype(&__78201138_tobii_research_get_all_eye_tracking_modes) tobii_research_get_all_eye_tracking_modes;
#undef tobii_research_get_all_gaze_output_frequencies
extern decltype(&__0d26724a_tobii_research_get_all_gaze_output_frequencies) tobii_research_get_all_gaze_output_frequencies;
#undef tobii_research_get_capabilities
extern decltype(&__09300a6c_tobii_research_get_capabilities) tobii_research_get_capabilities;
#undef tobii_research_get_device_name
extern decltype(&__0505767f_tobii_research_get_device_name) tobii_research_get_device_name;
#undef tobii_research_get_display_area
extern decltype(&__12263f70_tobii_research_get_display_area) tobii_research_get_display_area;
#undef tobii_research_get_eye_tracking_mode
extern decltype(&__674c4e59_tobii_research_get_eye_tracking_mode) tobii_research_get_eye_tracking_mode;
#undef tobii_research_get_firmware_version
extern decltype(&__7f436524_tobii_research_get_firmware_version) tobii_research_get_firmware_version;
#undef tobii_research_get_gaze_output_frequency
extern decltype(&__04392d3b_tobii_research_get_gaze_output_frequency) tobii_research_get_gaze_output_frequency;
#undef tobii_research_get_hmd_lens_configuration
extern decltype(&__653f2f39_tobii_research_get_hmd_lens_configuration) tobii_research_get_hmd_lens_configuration;
#undef tobii_research_get_model
extern decltype(&__072d1418_tobii_research_get_model) tobii_research_get_model;
#undef tobii_research_get_serial_number
extern decltype(&__0c06130c_tobii_research_get_serial_number) tobii_research_get_serial_number;
#undef tobii_research_get_track_box
extern decltype(&__454a7d7e_tobii_research_get_track_box) tobii_research_get_track_box;
#undef tobii_research_retrieve_calibration_data
extern decltype(&__01222e19_tobii_research_retrieve_calibration_data) tobii_research_retrieve_calibration_data;
#undef tobii_research_set_device_name
extern decltype(&__0505766b_tobii_research_set_device_name) tobii_research_set_device_name;
#undef tobii_research_set_eye_tracking_mode
extern decltype(&__674c4e4d_tobii_research_set_eye_tracking_mode) tobii_research_set_eye_tracking_mode;
#undef tobii_research_set_gaze_output_frequency
extern decltype(&__04392d2f_tobii_research_set_gaze_output_frequency) tobii_research_set_gaze_output_frequency;
#undef tobii_research_set_hmd_lens_configuration
extern decltype(&__653f2f2d_tobii_research_set_hmd_lens_configuration) tobii_research_set_hmd_lens_configuration;

#endif // STATIC_LIBTOBII_RESEARCH

namespace Dylib { bool tobii_research_Loaded(); }

#endif // TOBII_RESEARCH_IMPORTS_H
