// Import definitions for tobii_research library
// generated Tue Aug 08 15:59:35 2017 by DylibTool
#ifndef TOBII_RESEARCH_STREAM_IMPORTS_H
#define TOBII_RESEARCH_STREAM_IMPORTS_H

#include "Win32Defs.h"

#ifndef STATIC_LIBTOBII_RESEARCH
// Disable function declarations in the original header
// file by #defining function names to point to symbols that
// are not referenced by any code.
#define tobii_research_subscribe_to_external_signal_data __17273404_tobii_research_subscribe_to_external_signal_data
#define tobii_research_subscribe_to_eye_image __3c56546c_tobii_research_subscribe_to_eye_image
#define tobii_research_subscribe_to_eye_image_as_gif __636e5c79_tobii_research_subscribe_to_eye_image_as_gif
#define tobii_research_subscribe_to_gaze_data __0c474b45_tobii_research_subscribe_to_gaze_data
#define tobii_research_subscribe_to_hmd_gaze_data __642a2f1a_tobii_research_subscribe_to_hmd_gaze_data
#define tobii_research_subscribe_to_notifications __5a2d2832_tobii_research_subscribe_to_notifications
#define tobii_research_subscribe_to_stream_errors __46291226_tobii_research_subscribe_to_stream_errors
#define tobii_research_subscribe_to_time_synchronization_data __3954424b_tobii_research_subscribe_to_time_synchronization_data
#define tobii_research_unsubscribe_from_external_signal_data __42427f69_tobii_research_unsubscribe_from_external_signal_data
#define tobii_research_unsubscribe_from_eye_image __69331f01_tobii_research_unsubscribe_from_eye_image
#define tobii_research_unsubscribe_from_eye_image_as_gif __360b1714_tobii_research_unsubscribe_from_eye_image_as_gif
#define tobii_research_unsubscribe_from_gaze_data __59220028_tobii_research_unsubscribe_from_gaze_data
#define tobii_research_unsubscribe_from_hmd_gaze_data __314f6477_tobii_research_unsubscribe_from_hmd_gaze_data
#define tobii_research_unsubscribe_from_notifications __0f48635f_tobii_research_unsubscribe_from_notifications
#define tobii_research_unsubscribe_from_stream_errors __134c594b_tobii_research_unsubscribe_from_stream_errors
#define tobii_research_unsubscribe_from_time_synchronization_data __6c310926_tobii_research_unsubscribe_from_time_synchronization_data

#define __declspec(x)
#endif // STATIC_LIBTOBII_RESEARCH

#include "tobii_research_streams.h"

#ifndef STATIC_LIBTOBII_RESEARCH
#undef __declspec
// Use #undef to restore function names before declaring
// function pointers with the names originally used to
// declare imports.
#undef tobii_research_subscribe_to_external_signal_data
extern decltype(&__17273404_tobii_research_subscribe_to_external_signal_data) tobii_research_subscribe_to_external_signal_data;
#undef tobii_research_subscribe_to_eye_image
extern decltype(&__3c56546c_tobii_research_subscribe_to_eye_image) tobii_research_subscribe_to_eye_image;
#undef tobii_research_subscribe_to_eye_image_as_gif
extern decltype(&__636e5c79_tobii_research_subscribe_to_eye_image_as_gif) tobii_research_subscribe_to_eye_image_as_gif;
#undef tobii_research_subscribe_to_gaze_data
extern decltype(&__0c474b45_tobii_research_subscribe_to_gaze_data) tobii_research_subscribe_to_gaze_data;
#undef tobii_research_subscribe_to_hmd_gaze_data
extern decltype(&__642a2f1a_tobii_research_subscribe_to_hmd_gaze_data) tobii_research_subscribe_to_hmd_gaze_data;
#undef tobii_research_subscribe_to_notifications
extern decltype(&__5a2d2832_tobii_research_subscribe_to_notifications) tobii_research_subscribe_to_notifications;
#undef tobii_research_subscribe_to_stream_errors
extern decltype(&__46291226_tobii_research_subscribe_to_stream_errors) tobii_research_subscribe_to_stream_errors;
#undef tobii_research_subscribe_to_time_synchronization_data
extern decltype(&__3954424b_tobii_research_subscribe_to_time_synchronization_data) tobii_research_subscribe_to_time_synchronization_data;
#undef tobii_research_unsubscribe_from_external_signal_data
extern decltype(&__42427f69_tobii_research_unsubscribe_from_external_signal_data) tobii_research_unsubscribe_from_external_signal_data;
#undef tobii_research_unsubscribe_from_eye_image
extern decltype(&__69331f01_tobii_research_unsubscribe_from_eye_image) tobii_research_unsubscribe_from_eye_image;
#undef tobii_research_unsubscribe_from_eye_image_as_gif
extern decltype(&__360b1714_tobii_research_unsubscribe_from_eye_image_as_gif) tobii_research_unsubscribe_from_eye_image_as_gif;
#undef tobii_research_unsubscribe_from_gaze_data
extern decltype(&__59220028_tobii_research_unsubscribe_from_gaze_data) tobii_research_unsubscribe_from_gaze_data;
#undef tobii_research_unsubscribe_from_hmd_gaze_data
extern decltype(&__314f6477_tobii_research_unsubscribe_from_hmd_gaze_data) tobii_research_unsubscribe_from_hmd_gaze_data;
#undef tobii_research_unsubscribe_from_notifications
extern decltype(&__0f48635f_tobii_research_unsubscribe_from_notifications) tobii_research_unsubscribe_from_notifications;
#undef tobii_research_unsubscribe_from_stream_errors
extern decltype(&__134c594b_tobii_research_unsubscribe_from_stream_errors) tobii_research_unsubscribe_from_stream_errors;
#undef tobii_research_unsubscribe_from_time_synchronization_data
extern decltype(&__6c310926_tobii_research_unsubscribe_from_time_synchronization_data) tobii_research_unsubscribe_from_time_synchronization_data;

#endif // STATIC_LIBTOBII_RESEARCH

namespace Dylib { bool tobii_research_stream_Loaded(); }

#endif // TOBII_RESEARCH_IMPORTS_H
