// Import declarations for gSTIMbox.h, generated by dylib_imports.sh
#ifndef gSTIMbox_IMPORTS_H
#define gSTIMbox_IMPORTS_H

#include "Win32Defs.h"

#define gSTIMboxinit gSTIMboxinit_d909
#define gSTIMboxreset gSTIMboxreset_e2a8
#define gSTIMboxsetMode gSTIMboxsetMode_e204
#define gSTIMboxsetPortState gSTIMboxsetPortState_94a9
#define gSTIMboxsetFrequency gSTIMboxsetFrequency_ec40
#define gSTIMboxclose gSTIMboxclose_9a89
#define gSTIMboxgetHWVersion gSTIMboxgetHWVersion_aefe
#define gSTIMboxgetDriverVersion gSTIMboxgetDriverVersion_f632
#define gSTIMboxgetConnStatus gSTIMboxgetConnStatus_cada
#define gSTIMboxgetInputs gSTIMboxgetInputs_b7bb
#define gSTIMboxstartInputMonitoring gSTIMboxstartInputMonitoring_3978
#define gSTIMboxstopInputMonitoring gSTIMboxstopInputMonitoring_2d71
#define gSTIMboxsetInputInversion gSTIMboxsetInputInversion_86cb
#define gSTIMboxgetInputSamplerate gSTIMboxgetInputSamplerate_87e1
#define gSTIMboxgetInputFramelength gSTIMboxgetInputFramelength_5192
#define gSTIMboxgetErrorMessage gSTIMboxgetErrorMessage_d512

#include "gSTIMbox.h"

#undef gSTIMboxinit
#undef gSTIMboxreset
#undef gSTIMboxsetMode
#undef gSTIMboxsetPortState
#undef gSTIMboxsetFrequency
#undef gSTIMboxclose
#undef gSTIMboxgetHWVersion
#undef gSTIMboxgetDriverVersion
#undef gSTIMboxgetConnStatus
#undef gSTIMboxgetInputs
#undef gSTIMboxstartInputMonitoring
#undef gSTIMboxstopInputMonitoring
#undef gSTIMboxsetInputInversion
#undef gSTIMboxgetInputSamplerate
#undef gSTIMboxgetInputFramelength
#undef gSTIMboxgetErrorMessage

extern "C" {
extern int ( *gSTIMboxinit)(HANDLE *com, int comport, int inputSR, int inputFrame, int blocking);
extern int ( *gSTIMboxreset)(HANDLE com);
extern int ( *gSTIMboxsetMode)(HANDLE com, int nrPorts, int port[], int mode[]);
extern int ( *gSTIMboxsetPortState)(HANDLE com, int nrPorts, int port[], int state[]);
extern int ( *gSTIMboxsetFrequency)(HANDLE com, int nrPorts, int port[], double freq[]);
extern int ( *gSTIMboxclose)(HANDLE com);
extern int ( *gSTIMboxgetHWVersion)(HANDLE com, float &HWVersion);
extern int ( *gSTIMboxgetDriverVersion)(double &DriverVersion);
extern int ( *gSTIMboxgetConnStatus)(HANDLE com, int &status);
extern int ( *gSTIMboxgetInputs)(HANDLE com, int *buffer, int &overUnderflow);
extern int ( *gSTIMboxstartInputMonitoring)(HANDLE com);
extern int ( *gSTIMboxstopInputMonitoring)(HANDLE com);
extern int ( *gSTIMboxsetInputInversion)(HANDLE com, int inversion);
extern int ( *gSTIMboxgetInputSamplerate)(HANDLE com, int &sr);
extern int ( *gSTIMboxgetInputFramelength)(HANDLE com, int &fl);
extern int ( *gSTIMboxgetErrorMessage)(int error, int messagelength, char *errormessage);
}

namespace Dylib { bool gSTIMbox_Loaded(); }

#endif // gSTIMbox_IMPORTS_H
