#ifndef VHT_DEVICE_TYPES_H
#define VHT_DEVICE_TYPES_H

typedef enum { 
    VHT_DEVICE  =   0x0000,
    VHT_GLOVE   =   0x1000,
    VHT_TRACKER =   0x2000,
    VHT_CYBERGLOVE = VHT_GLOVE | 0x0001, 
    VHT_CYBERTOUCH = VHT_GLOVE | 0x0002,
    VHT_CYBERGRASP = VHT_GLOVE | 0x0004,
    VHT_ASCENSION  = VHT_TRACKER | 0x0001,
    VHT_POLHEMUS   = VHT_TRACKER | 0x0002,
    VHT_FORCETRAK  = VHT_TRACKER | 0x0003
} vhtDeviceType;

#endif


