// Import declarations for avfilter-5 library
// generated by C:\BCI2000.svn\build\buildutils\create_import_table.exe from win32-x86/dynamic/avfilter-5.dll
#if STATIC_LIBAVFILTER_5

namespace Dylib { bool avfilter_5_Loaded() { return true; } }
extern "C" {
}

#else

#include "DylibImports.h"
namespace { extern const Dylib::Import* functionImports; }

// Here you may specify a custom error message to be displayed when the library cannot be found.
static const char* notFoundMsg = "";
// Here you may specify an URL to some local or remote help resource.
static const char* notFoundURL = "";
RegisterDylibWithAliases( avfilter_5, "avfilter-5", functionImports, notFoundMsg, notFoundURL );

extern "C" {

// NOTE: When loading the library, function bodies will be overwritten with absolute jumps
// to imported functions, i.e. function bodies must be roughly 2 * sizeof(void*) bytes long.
// A call to a member function with a pointer argument should be large enough.
// 
// In addition, having distinct function bodies for each function stub
// is important -- that makes it impossible for size optimizers to
// collapse them into a single definition.
//
void av_buffersink_get_frame() { Dylib::avfilter_5.UninitializedFunctionExport( "av_buffersink_get_frame" ); }
void av_buffersink_get_samples() { Dylib::avfilter_5.UninitializedFunctionExport( "av_buffersink_get_samples" ); }
void av_buffersink_read() { Dylib::avfilter_5.UninitializedFunctionExport( "av_buffersink_read" ); }
void av_buffersink_read_samples() { Dylib::avfilter_5.UninitializedFunctionExport( "av_buffersink_read_samples" ); }
void av_buffersrc_add_frame() { Dylib::avfilter_5.UninitializedFunctionExport( "av_buffersrc_add_frame" ); }
void av_buffersrc_buffer() { Dylib::avfilter_5.UninitializedFunctionExport( "av_buffersrc_buffer" ); }
void av_buffersrc_write_frame() { Dylib::avfilter_5.UninitializedFunctionExport( "av_buffersrc_write_frame" ); }
void av_filter_next() { Dylib::avfilter_5.UninitializedFunctionExport( "av_filter_next" ); }
void avfilter_config_links() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_config_links" ); }
void avfilter_configuration() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_configuration" ); }
void avfilter_copy_buf_props() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_copy_buf_props" ); }
void avfilter_copy_buffer_ref_props() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_copy_buffer_ref_props" ); }
void avfilter_copy_frame_props() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_copy_frame_props" ); }
void avfilter_free() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_free" ); }
void avfilter_get_audio_buffer_ref_from_arrays() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_get_audio_buffer_ref_from_arrays" ); }
void avfilter_get_by_name() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_get_by_name" ); }
void avfilter_get_class() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_get_class" ); }
void avfilter_get_video_buffer_ref_from_arrays() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_get_video_buffer_ref_from_arrays" ); }
void avfilter_graph_add_filter() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_graph_add_filter" ); }
void avfilter_graph_alloc() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_graph_alloc" ); }
void avfilter_graph_alloc_filter() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_graph_alloc_filter" ); }
void avfilter_graph_config() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_graph_config" ); }
void avfilter_graph_create_filter() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_graph_create_filter" ); }
void avfilter_graph_free() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_graph_free" ); }
void avfilter_graph_get_filter() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_graph_get_filter" ); }
void avfilter_graph_parse() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_graph_parse" ); }
void avfilter_graph_parse2() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_graph_parse2" ); }
void avfilter_init_dict() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_init_dict" ); }
void avfilter_init_filter() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_init_filter" ); }
void avfilter_init_str() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_init_str" ); }
void avfilter_inout_alloc() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_inout_alloc" ); }
void avfilter_inout_free() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_inout_free" ); }
void avfilter_insert_filter() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_insert_filter" ); }
void avfilter_license() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_license" ); }
void avfilter_link() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_link" ); }
void avfilter_next() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_next" ); }
void avfilter_open() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_open" ); }
void avfilter_pad_count() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_pad_count" ); }
void avfilter_pad_get_name() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_pad_get_name" ); }
void avfilter_pad_get_type() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_pad_get_type" ); }
void avfilter_ref_buffer() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_ref_buffer" ); }
void avfilter_register() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_register" ); }
void avfilter_register_all() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_register_all" ); }
void avfilter_uninit() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_uninit" ); }
void avfilter_unref_buffer() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_unref_buffer" ); }
void avfilter_unref_bufferp() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_unref_bufferp" ); }
void avfilter_version() { Dylib::avfilter_5.UninitializedFunctionExport( "avfilter_version" ); }
}

namespace {
const Dylib::Import functionImports_[] =
{
  { "av_buffersink_get_frame", (void**)&av_buffersink_get_frame, Dylib::Import::functionStub },
  { "av_buffersink_get_samples", (void**)&av_buffersink_get_samples, Dylib::Import::functionStub },
  { "av_buffersink_read", (void**)&av_buffersink_read, Dylib::Import::functionStub },
  { "av_buffersink_read_samples", (void**)&av_buffersink_read_samples, Dylib::Import::functionStub },
  { "av_buffersrc_add_frame", (void**)&av_buffersrc_add_frame, Dylib::Import::functionStub },
  { "av_buffersrc_buffer", (void**)&av_buffersrc_buffer, Dylib::Import::functionStub },
  { "av_buffersrc_write_frame", (void**)&av_buffersrc_write_frame, Dylib::Import::functionStub },
  { "av_filter_next", (void**)&av_filter_next, Dylib::Import::functionStub },
  { "avfilter_config_links", (void**)&avfilter_config_links, Dylib::Import::functionStub },
  { "avfilter_configuration", (void**)&avfilter_configuration, Dylib::Import::functionStub },
  { "avfilter_copy_buf_props", (void**)&avfilter_copy_buf_props, Dylib::Import::functionStub },
  { "avfilter_copy_buffer_ref_props", (void**)&avfilter_copy_buffer_ref_props, Dylib::Import::functionStub },
  { "avfilter_copy_frame_props", (void**)&avfilter_copy_frame_props, Dylib::Import::functionStub },
  { "avfilter_free", (void**)&avfilter_free, Dylib::Import::functionStub },
  { "avfilter_get_audio_buffer_ref_from_arrays", (void**)&avfilter_get_audio_buffer_ref_from_arrays, Dylib::Import::functionStub },
  { "avfilter_get_by_name", (void**)&avfilter_get_by_name, Dylib::Import::functionStub },
  { "avfilter_get_class", (void**)&avfilter_get_class, Dylib::Import::functionStub },
  { "avfilter_get_video_buffer_ref_from_arrays", (void**)&avfilter_get_video_buffer_ref_from_arrays, Dylib::Import::functionStub },
  { "avfilter_graph_add_filter", (void**)&avfilter_graph_add_filter, Dylib::Import::functionStub },
  { "avfilter_graph_alloc", (void**)&avfilter_graph_alloc, Dylib::Import::functionStub },
  { "avfilter_graph_alloc_filter", (void**)&avfilter_graph_alloc_filter, Dylib::Import::functionStub },
  { "avfilter_graph_config", (void**)&avfilter_graph_config, Dylib::Import::functionStub },
  { "avfilter_graph_create_filter", (void**)&avfilter_graph_create_filter, Dylib::Import::functionStub },
  { "avfilter_graph_free", (void**)&avfilter_graph_free, Dylib::Import::functionStub },
  { "avfilter_graph_get_filter", (void**)&avfilter_graph_get_filter, Dylib::Import::functionStub },
  { "avfilter_graph_parse", (void**)&avfilter_graph_parse, Dylib::Import::functionStub },
  { "avfilter_graph_parse2", (void**)&avfilter_graph_parse2, Dylib::Import::functionStub },
  { "avfilter_init_dict", (void**)&avfilter_init_dict, Dylib::Import::functionStub },
  { "avfilter_init_filter", (void**)&avfilter_init_filter, Dylib::Import::functionStub },
  { "avfilter_init_str", (void**)&avfilter_init_str, Dylib::Import::functionStub },
  { "avfilter_inout_alloc", (void**)&avfilter_inout_alloc, Dylib::Import::functionStub },
  { "avfilter_inout_free", (void**)&avfilter_inout_free, Dylib::Import::functionStub },
  { "avfilter_insert_filter", (void**)&avfilter_insert_filter, Dylib::Import::functionStub },
  { "avfilter_license", (void**)&avfilter_license, Dylib::Import::functionStub },
  { "avfilter_link", (void**)&avfilter_link, Dylib::Import::functionStub },
  { "avfilter_next", (void**)&avfilter_next, Dylib::Import::functionStub },
  { "avfilter_open", (void**)&avfilter_open, Dylib::Import::functionStub },
  { "avfilter_pad_count", (void**)&avfilter_pad_count, Dylib::Import::functionStub },
  { "avfilter_pad_get_name", (void**)&avfilter_pad_get_name, Dylib::Import::functionStub },
  { "avfilter_pad_get_type", (void**)&avfilter_pad_get_type, Dylib::Import::functionStub },
  { "avfilter_ref_buffer", (void**)&avfilter_ref_buffer, Dylib::Import::functionStub },
  { "avfilter_register", (void**)&avfilter_register, Dylib::Import::functionStub },
  { "avfilter_register_all", (void**)&avfilter_register_all, Dylib::Import::functionStub },
  { "avfilter_uninit", (void**)&avfilter_uninit, Dylib::Import::functionStub },
  { "avfilter_unref_buffer", (void**)&avfilter_unref_buffer, Dylib::Import::functionStub },
  { "avfilter_unref_bufferp", (void**)&avfilter_unref_bufferp, Dylib::Import::functionStub },
  { "avfilter_version", (void**)&avfilter_version, Dylib::Import::functionStub },
  { 0, 0, 0 }
};
const Dylib::Import* functionImports = functionImports_;
}

#endif // STATIC_LIBAVFILTER_5

