// Import declarations for avutil-54 library
// generated by C:\BCI2000.svn\build\buildutils\create_import_table.exe from win32-x86/dynamic/avutil-54.dll
#if STATIC_LIBAVUTIL_54

namespace Dylib { bool avutil_54_Loaded() { return true; } }
extern "C" {
void* p_av_aes_size = &av_aes_size;
void* p_av_md5_size = &av_md5_size;
void* p_av_pix_fmt_descriptors = &av_pix_fmt_descriptors;
void* p_av_reverse = &av_reverse;
void* p_av_sha_size = &av_sha_size;
void* p_av_tree_node_size = &av_tree_node_size;
}

#else

#include "DylibImports.h"
namespace { extern const Dylib::Import* functionImports; }

// Here you may specify a custom error message to be displayed when the library cannot be found.
static const char* notFoundMsg = "";
// Here you may specify an URL to some local or remote help resource.
static const char* notFoundURL = "";
RegisterDylibWithAliases( avutil_54, "avutil-54", functionImports, notFoundMsg, notFoundURL );

extern "C" {
void* p_av_aes_size = Dylib::avutil_54.ResolveDataExport( "av_aes_size" );
void* p_av_md5_size = Dylib::avutil_54.ResolveDataExport( "av_md5_size" );
void* p_av_pix_fmt_descriptors = Dylib::avutil_54.ResolveDataExport( "av_pix_fmt_descriptors" );
void* p_av_reverse = Dylib::avutil_54.ResolveDataExport( "av_reverse" );
void* p_av_sha_size = Dylib::avutil_54.ResolveDataExport( "av_sha_size" );
void* p_av_tree_node_size = Dylib::avutil_54.ResolveDataExport( "av_tree_node_size" );

// NOTE: When loading the library, function bodies will be overwritten with absolute jumps
// to imported functions, i.e. function bodies must be roughly 2 * sizeof(void*) bytes long.
// A call to a member function with a pointer argument should be large enough.
// 
// In addition, having distinct function bodies for each function stub
// is important -- that makes it impossible for size optimizers to
// collapse them into a single definition.
//
void av_add_q() { Dylib::avutil_54.UninitializedFunctionExport( "av_add_q" ); }
void av_adler32_update() { Dylib::avutil_54.UninitializedFunctionExport( "av_adler32_update" ); }
void av_aes_alloc() { Dylib::avutil_54.UninitializedFunctionExport( "av_aes_alloc" ); }
void av_aes_crypt() { Dylib::avutil_54.UninitializedFunctionExport( "av_aes_crypt" ); }
void av_aes_init() { Dylib::avutil_54.UninitializedFunctionExport( "av_aes_init" ); }
void av_audio_fifo_alloc() { Dylib::avutil_54.UninitializedFunctionExport( "av_audio_fifo_alloc" ); }
void av_audio_fifo_drain() { Dylib::avutil_54.UninitializedFunctionExport( "av_audio_fifo_drain" ); }
void av_audio_fifo_free() { Dylib::avutil_54.UninitializedFunctionExport( "av_audio_fifo_free" ); }
void av_audio_fifo_read() { Dylib::avutil_54.UninitializedFunctionExport( "av_audio_fifo_read" ); }
void av_audio_fifo_realloc() { Dylib::avutil_54.UninitializedFunctionExport( "av_audio_fifo_realloc" ); }
void av_audio_fifo_reset() { Dylib::avutil_54.UninitializedFunctionExport( "av_audio_fifo_reset" ); }
void av_audio_fifo_size() { Dylib::avutil_54.UninitializedFunctionExport( "av_audio_fifo_size" ); }
void av_audio_fifo_space() { Dylib::avutil_54.UninitializedFunctionExport( "av_audio_fifo_space" ); }
void av_audio_fifo_write() { Dylib::avutil_54.UninitializedFunctionExport( "av_audio_fifo_write" ); }
void av_base64_decode() { Dylib::avutil_54.UninitializedFunctionExport( "av_base64_decode" ); }
void av_base64_encode() { Dylib::avutil_54.UninitializedFunctionExport( "av_base64_encode" ); }
void av_basename() { Dylib::avutil_54.UninitializedFunctionExport( "av_basename" ); }
void av_blowfish_crypt() { Dylib::avutil_54.UninitializedFunctionExport( "av_blowfish_crypt" ); }
void av_blowfish_crypt_ecb() { Dylib::avutil_54.UninitializedFunctionExport( "av_blowfish_crypt_ecb" ); }
void av_blowfish_init() { Dylib::avutil_54.UninitializedFunctionExport( "av_blowfish_init" ); }
void av_bmg_get() { Dylib::avutil_54.UninitializedFunctionExport( "av_bmg_get" ); }
void av_buffer_alloc() { Dylib::avutil_54.UninitializedFunctionExport( "av_buffer_alloc" ); }
void av_buffer_allocz() { Dylib::avutil_54.UninitializedFunctionExport( "av_buffer_allocz" ); }
void av_buffer_create() { Dylib::avutil_54.UninitializedFunctionExport( "av_buffer_create" ); }
void av_buffer_default_free() { Dylib::avutil_54.UninitializedFunctionExport( "av_buffer_default_free" ); }
void av_buffer_is_writable() { Dylib::avutil_54.UninitializedFunctionExport( "av_buffer_is_writable" ); }
void av_buffer_make_writable() { Dylib::avutil_54.UninitializedFunctionExport( "av_buffer_make_writable" ); }
void av_buffer_pool_get() { Dylib::avutil_54.UninitializedFunctionExport( "av_buffer_pool_get" ); }
void av_buffer_pool_init() { Dylib::avutil_54.UninitializedFunctionExport( "av_buffer_pool_init" ); }
void av_buffer_pool_uninit() { Dylib::avutil_54.UninitializedFunctionExport( "av_buffer_pool_uninit" ); }
void av_buffer_realloc() { Dylib::avutil_54.UninitializedFunctionExport( "av_buffer_realloc" ); }
void av_buffer_ref() { Dylib::avutil_54.UninitializedFunctionExport( "av_buffer_ref" ); }
void av_buffer_unref() { Dylib::avutil_54.UninitializedFunctionExport( "av_buffer_unref" ); }
void av_channel_layout_extract_channel() { Dylib::avutil_54.UninitializedFunctionExport( "av_channel_layout_extract_channel" ); }
void av_compare_mod() { Dylib::avutil_54.UninitializedFunctionExport( "av_compare_mod" ); }
void av_compare_ts() { Dylib::avutil_54.UninitializedFunctionExport( "av_compare_ts" ); }
void av_cpu_count() { Dylib::avutil_54.UninitializedFunctionExport( "av_cpu_count" ); }
void av_crc() { Dylib::avutil_54.UninitializedFunctionExport( "av_crc" ); }
void av_crc_get_table() { Dylib::avutil_54.UninitializedFunctionExport( "av_crc_get_table" ); }
void av_crc_init() { Dylib::avutil_54.UninitializedFunctionExport( "av_crc_init" ); }
void av_ctz() { Dylib::avutil_54.UninitializedFunctionExport( "av_ctz" ); }
void av_d2q() { Dylib::avutil_54.UninitializedFunctionExport( "av_d2q" ); }
void av_d2str() { Dylib::avutil_54.UninitializedFunctionExport( "av_d2str" ); }
void av_default_item_name() { Dylib::avutil_54.UninitializedFunctionExport( "av_default_item_name" ); }
void av_des_crypt() { Dylib::avutil_54.UninitializedFunctionExport( "av_des_crypt" ); }
void av_des_init() { Dylib::avutil_54.UninitializedFunctionExport( "av_des_init" ); }
void av_des_mac() { Dylib::avutil_54.UninitializedFunctionExport( "av_des_mac" ); }
void av_dict_copy() { Dylib::avutil_54.UninitializedFunctionExport( "av_dict_copy" ); }
void av_dict_count() { Dylib::avutil_54.UninitializedFunctionExport( "av_dict_count" ); }
void av_dict_free() { Dylib::avutil_54.UninitializedFunctionExport( "av_dict_free" ); }
void av_dict_get() { Dylib::avutil_54.UninitializedFunctionExport( "av_dict_get" ); }
void av_dict_parse_string() { Dylib::avutil_54.UninitializedFunctionExport( "av_dict_parse_string" ); }
void av_dict_set() { Dylib::avutil_54.UninitializedFunctionExport( "av_dict_set" ); }
void av_dirname() { Dylib::avutil_54.UninitializedFunctionExport( "av_dirname" ); }
void av_display_matrix_flip() { Dylib::avutil_54.UninitializedFunctionExport( "av_display_matrix_flip" ); }
void av_display_rotation_get() { Dylib::avutil_54.UninitializedFunctionExport( "av_display_rotation_get" ); }
void av_display_rotation_set() { Dylib::avutil_54.UninitializedFunctionExport( "av_display_rotation_set" ); }
void av_div_q() { Dylib::avutil_54.UninitializedFunctionExport( "av_div_q" ); }
void av_downmix_info_update_side_data() { Dylib::avutil_54.UninitializedFunctionExport( "av_downmix_info_update_side_data" ); }
void av_evaluate_lls() { Dylib::avutil_54.UninitializedFunctionExport( "av_evaluate_lls" ); }
void av_expr_eval() { Dylib::avutil_54.UninitializedFunctionExport( "av_expr_eval" ); }
void av_expr_free() { Dylib::avutil_54.UninitializedFunctionExport( "av_expr_free" ); }
void av_expr_parse() { Dylib::avutil_54.UninitializedFunctionExport( "av_expr_parse" ); }
void av_expr_parse_and_eval() { Dylib::avutil_54.UninitializedFunctionExport( "av_expr_parse_and_eval" ); }
void av_fast_malloc() { Dylib::avutil_54.UninitializedFunctionExport( "av_fast_malloc" ); }
void av_fast_realloc() { Dylib::avutil_54.UninitializedFunctionExport( "av_fast_realloc" ); }
void av_fifo_alloc() { Dylib::avutil_54.UninitializedFunctionExport( "av_fifo_alloc" ); }
void av_fifo_drain() { Dylib::avutil_54.UninitializedFunctionExport( "av_fifo_drain" ); }
void av_fifo_free() { Dylib::avutil_54.UninitializedFunctionExport( "av_fifo_free" ); }
void av_fifo_generic_read() { Dylib::avutil_54.UninitializedFunctionExport( "av_fifo_generic_read" ); }
void av_fifo_generic_write() { Dylib::avutil_54.UninitializedFunctionExport( "av_fifo_generic_write" ); }
void av_fifo_realloc2() { Dylib::avutil_54.UninitializedFunctionExport( "av_fifo_realloc2" ); }
void av_fifo_reset() { Dylib::avutil_54.UninitializedFunctionExport( "av_fifo_reset" ); }
void av_fifo_size() { Dylib::avutil_54.UninitializedFunctionExport( "av_fifo_size" ); }
void av_fifo_space() { Dylib::avutil_54.UninitializedFunctionExport( "av_fifo_space" ); }
void av_file_map() { Dylib::avutil_54.UninitializedFunctionExport( "av_file_map" ); }
void av_file_unmap() { Dylib::avutil_54.UninitializedFunctionExport( "av_file_unmap" ); }
void av_find_info_tag() { Dylib::avutil_54.UninitializedFunctionExport( "av_find_info_tag" ); }
void av_find_nearest_q_idx() { Dylib::avutil_54.UninitializedFunctionExport( "av_find_nearest_q_idx" ); }
void av_frame_alloc() { Dylib::avutil_54.UninitializedFunctionExport( "av_frame_alloc" ); }
void av_frame_clone() { Dylib::avutil_54.UninitializedFunctionExport( "av_frame_clone" ); }
void av_frame_copy() { Dylib::avutil_54.UninitializedFunctionExport( "av_frame_copy" ); }
void av_frame_copy_props() { Dylib::avutil_54.UninitializedFunctionExport( "av_frame_copy_props" ); }
void av_frame_free() { Dylib::avutil_54.UninitializedFunctionExport( "av_frame_free" ); }
void av_frame_get_buffer() { Dylib::avutil_54.UninitializedFunctionExport( "av_frame_get_buffer" ); }
void av_frame_get_plane_buffer() { Dylib::avutil_54.UninitializedFunctionExport( "av_frame_get_plane_buffer" ); }
void av_frame_get_side_data() { Dylib::avutil_54.UninitializedFunctionExport( "av_frame_get_side_data" ); }
void av_frame_is_writable() { Dylib::avutil_54.UninitializedFunctionExport( "av_frame_is_writable" ); }
void av_frame_make_writable() { Dylib::avutil_54.UninitializedFunctionExport( "av_frame_make_writable" ); }
void av_frame_move_ref() { Dylib::avutil_54.UninitializedFunctionExport( "av_frame_move_ref" ); }
void av_frame_new_side_data() { Dylib::avutil_54.UninitializedFunctionExport( "av_frame_new_side_data" ); }
void av_frame_ref() { Dylib::avutil_54.UninitializedFunctionExport( "av_frame_ref" ); }
void av_frame_remove_side_data() { Dylib::avutil_54.UninitializedFunctionExport( "av_frame_remove_side_data" ); }
void av_frame_unref() { Dylib::avutil_54.UninitializedFunctionExport( "av_frame_unref" ); }
void av_free() { Dylib::avutil_54.UninitializedFunctionExport( "av_free" ); }
void av_freep() { Dylib::avutil_54.UninitializedFunctionExport( "av_freep" ); }
void av_gcd() { Dylib::avutil_54.UninitializedFunctionExport( "av_gcd" ); }
void av_get_bits_per_pixel() { Dylib::avutil_54.UninitializedFunctionExport( "av_get_bits_per_pixel" ); }
void av_get_bytes_per_sample() { Dylib::avutil_54.UninitializedFunctionExport( "av_get_bytes_per_sample" ); }
void av_get_channel_layout() { Dylib::avutil_54.UninitializedFunctionExport( "av_get_channel_layout" ); }
void av_get_channel_layout_channel_index() { Dylib::avutil_54.UninitializedFunctionExport( "av_get_channel_layout_channel_index" ); }
void av_get_channel_layout_nb_channels() { Dylib::avutil_54.UninitializedFunctionExport( "av_get_channel_layout_nb_channels" ); }
void av_get_channel_layout_string() { Dylib::avutil_54.UninitializedFunctionExport( "av_get_channel_layout_string" ); }
void av_get_channel_name() { Dylib::avutil_54.UninitializedFunctionExport( "av_get_channel_name" ); }
void av_get_cpu_flags() { Dylib::avutil_54.UninitializedFunctionExport( "av_get_cpu_flags" ); }
void av_get_default_channel_layout() { Dylib::avutil_54.UninitializedFunctionExport( "av_get_default_channel_layout" ); }
void av_get_packed_sample_fmt() { Dylib::avutil_54.UninitializedFunctionExport( "av_get_packed_sample_fmt" ); }
void av_get_picture_type_char() { Dylib::avutil_54.UninitializedFunctionExport( "av_get_picture_type_char" ); }
void av_get_pix_fmt() { Dylib::avutil_54.UninitializedFunctionExport( "av_get_pix_fmt" ); }
void av_get_pix_fmt_name() { Dylib::avutil_54.UninitializedFunctionExport( "av_get_pix_fmt_name" ); }
void av_get_pix_fmt_string() { Dylib::avutil_54.UninitializedFunctionExport( "av_get_pix_fmt_string" ); }
void av_get_planar_sample_fmt() { Dylib::avutil_54.UninitializedFunctionExport( "av_get_planar_sample_fmt" ); }
void av_get_random_seed() { Dylib::avutil_54.UninitializedFunctionExport( "av_get_random_seed" ); }
void av_get_sample_fmt() { Dylib::avutil_54.UninitializedFunctionExport( "av_get_sample_fmt" ); }
void av_get_sample_fmt_name() { Dylib::avutil_54.UninitializedFunctionExport( "av_get_sample_fmt_name" ); }
void av_get_sample_fmt_string() { Dylib::avutil_54.UninitializedFunctionExport( "av_get_sample_fmt_string" ); }
void av_get_time_base_q() { Dylib::avutil_54.UninitializedFunctionExport( "av_get_time_base_q" ); }
void av_get_token() { Dylib::avutil_54.UninitializedFunctionExport( "av_get_token" ); }
void av_gettime() { Dylib::avutil_54.UninitializedFunctionExport( "av_gettime" ); }
void av_hmac_alloc() { Dylib::avutil_54.UninitializedFunctionExport( "av_hmac_alloc" ); }
void av_hmac_calc() { Dylib::avutil_54.UninitializedFunctionExport( "av_hmac_calc" ); }
void av_hmac_final() { Dylib::avutil_54.UninitializedFunctionExport( "av_hmac_final" ); }
void av_hmac_free() { Dylib::avutil_54.UninitializedFunctionExport( "av_hmac_free" ); }
void av_hmac_init() { Dylib::avutil_54.UninitializedFunctionExport( "av_hmac_init" ); }
void av_hmac_update() { Dylib::avutil_54.UninitializedFunctionExport( "av_hmac_update" ); }
void av_image_alloc() { Dylib::avutil_54.UninitializedFunctionExport( "av_image_alloc" ); }
void av_image_check_sar() { Dylib::avutil_54.UninitializedFunctionExport( "av_image_check_sar" ); }
void av_image_check_size() { Dylib::avutil_54.UninitializedFunctionExport( "av_image_check_size" ); }
void av_image_copy() { Dylib::avutil_54.UninitializedFunctionExport( "av_image_copy" ); }
void av_image_copy_plane() { Dylib::avutil_54.UninitializedFunctionExport( "av_image_copy_plane" ); }
void av_image_fill_linesizes() { Dylib::avutil_54.UninitializedFunctionExport( "av_image_fill_linesizes" ); }
void av_image_fill_max_pixsteps() { Dylib::avutil_54.UninitializedFunctionExport( "av_image_fill_max_pixsteps" ); }
void av_image_fill_pointers() { Dylib::avutil_54.UninitializedFunctionExport( "av_image_fill_pointers" ); }
void av_image_get_linesize() { Dylib::avutil_54.UninitializedFunctionExport( "av_image_get_linesize" ); }
void av_init_lls() { Dylib::avutil_54.UninitializedFunctionExport( "av_init_lls" ); }
void av_isdigit() { Dylib::avutil_54.UninitializedFunctionExport( "av_isdigit" ); }
void av_isgraph() { Dylib::avutil_54.UninitializedFunctionExport( "av_isgraph" ); }
void av_isspace() { Dylib::avutil_54.UninitializedFunctionExport( "av_isspace" ); }
void av_isxdigit() { Dylib::avutil_54.UninitializedFunctionExport( "av_isxdigit" ); }
void av_lfg_init() { Dylib::avutil_54.UninitializedFunctionExport( "av_lfg_init" ); }
void av_log() { Dylib::avutil_54.UninitializedFunctionExport( "av_log" ); }
void av_log2() { Dylib::avutil_54.UninitializedFunctionExport( "av_log2" ); }
void av_log2_16bit() { Dylib::avutil_54.UninitializedFunctionExport( "av_log2_16bit" ); }
void av_log_default_callback() { Dylib::avutil_54.UninitializedFunctionExport( "av_log_default_callback" ); }
void av_log_get_level() { Dylib::avutil_54.UninitializedFunctionExport( "av_log_get_level" ); }
void av_log_set_callback() { Dylib::avutil_54.UninitializedFunctionExport( "av_log_set_callback" ); }
void av_log_set_flags() { Dylib::avutil_54.UninitializedFunctionExport( "av_log_set_flags" ); }
void av_log_set_level() { Dylib::avutil_54.UninitializedFunctionExport( "av_log_set_level" ); }
void av_lzo1x_decode() { Dylib::avutil_54.UninitializedFunctionExport( "av_lzo1x_decode" ); }
void av_malloc() { Dylib::avutil_54.UninitializedFunctionExport( "av_malloc" ); }
void av_mallocz() { Dylib::avutil_54.UninitializedFunctionExport( "av_mallocz" ); }
void av_match_name() { Dylib::avutil_54.UninitializedFunctionExport( "av_match_name" ); }
void av_md5_alloc() { Dylib::avutil_54.UninitializedFunctionExport( "av_md5_alloc" ); }
void av_md5_final() { Dylib::avutil_54.UninitializedFunctionExport( "av_md5_final" ); }
void av_md5_init() { Dylib::avutil_54.UninitializedFunctionExport( "av_md5_init" ); }
void av_md5_sum() { Dylib::avutil_54.UninitializedFunctionExport( "av_md5_sum" ); }
void av_md5_update() { Dylib::avutil_54.UninitializedFunctionExport( "av_md5_update" ); }
void av_memcpy_backptr() { Dylib::avutil_54.UninitializedFunctionExport( "av_memcpy_backptr" ); }
void av_mul_q() { Dylib::avutil_54.UninitializedFunctionExport( "av_mul_q" ); }
void av_nearer_q() { Dylib::avutil_54.UninitializedFunctionExport( "av_nearer_q" ); }
void av_opt_child_class_next() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_child_class_next" ); }
void av_opt_child_next() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_child_next" ); }
void av_opt_eval_double() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_eval_double" ); }
void av_opt_eval_flags() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_eval_flags" ); }
void av_opt_eval_float() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_eval_float" ); }
void av_opt_eval_int() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_eval_int" ); }
void av_opt_eval_int64() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_eval_int64" ); }
void av_opt_eval_q() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_eval_q" ); }
void av_opt_find() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_find" ); }
void av_opt_find2() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_find2" ); }
void av_opt_flag_is_set() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_flag_is_set" ); }
void av_opt_free() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_free" ); }
void av_opt_get() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_get" ); }
void av_opt_get_dict_val() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_get_dict_val" ); }
void av_opt_get_double() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_get_double" ); }
void av_opt_get_int() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_get_int" ); }
void av_opt_get_q() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_get_q" ); }
void av_opt_next() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_next" ); }
void av_opt_set() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_set" ); }
void av_opt_set_bin() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_set_bin" ); }
void av_opt_set_defaults() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_set_defaults" ); }
void av_opt_set_dict() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_set_dict" ); }
void av_opt_set_dict_val() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_set_dict_val" ); }
void av_opt_set_double() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_set_double" ); }
void av_opt_set_int() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_set_int" ); }
void av_opt_set_q() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_set_q" ); }
void av_opt_show2() { Dylib::avutil_54.UninitializedFunctionExport( "av_opt_show2" ); }
void av_parse_color() { Dylib::avutil_54.UninitializedFunctionExport( "av_parse_color" ); }
void av_parse_cpu_flags() { Dylib::avutil_54.UninitializedFunctionExport( "av_parse_cpu_flags" ); }
void av_parse_time() { Dylib::avutil_54.UninitializedFunctionExport( "av_parse_time" ); }
void av_parse_video_rate() { Dylib::avutil_54.UninitializedFunctionExport( "av_parse_video_rate" ); }
void av_parse_video_size() { Dylib::avutil_54.UninitializedFunctionExport( "av_parse_video_size" ); }
void av_pix_fmt_count_planes() { Dylib::avutil_54.UninitializedFunctionExport( "av_pix_fmt_count_planes" ); }
void av_pix_fmt_desc_get() { Dylib::avutil_54.UninitializedFunctionExport( "av_pix_fmt_desc_get" ); }
void av_pix_fmt_desc_get_id() { Dylib::avutil_54.UninitializedFunctionExport( "av_pix_fmt_desc_get_id" ); }
void av_pix_fmt_desc_next() { Dylib::avutil_54.UninitializedFunctionExport( "av_pix_fmt_desc_next" ); }
void av_pix_fmt_get_chroma_sub_sample() { Dylib::avutil_54.UninitializedFunctionExport( "av_pix_fmt_get_chroma_sub_sample" ); }
void av_pix_fmt_swap_endianness() { Dylib::avutil_54.UninitializedFunctionExport( "av_pix_fmt_swap_endianness" ); }
void av_rc4_crypt() { Dylib::avutil_54.UninitializedFunctionExport( "av_rc4_crypt" ); }
void av_rc4_init() { Dylib::avutil_54.UninitializedFunctionExport( "av_rc4_init" ); }
void av_read_image_line() { Dylib::avutil_54.UninitializedFunctionExport( "av_read_image_line" ); }
void av_realloc() { Dylib::avutil_54.UninitializedFunctionExport( "av_realloc" ); }
void av_realloc_array() { Dylib::avutil_54.UninitializedFunctionExport( "av_realloc_array" ); }
void av_reallocp() { Dylib::avutil_54.UninitializedFunctionExport( "av_reallocp" ); }
void av_reallocp_array() { Dylib::avutil_54.UninitializedFunctionExport( "av_reallocp_array" ); }
void av_reduce() { Dylib::avutil_54.UninitializedFunctionExport( "av_reduce" ); }
void av_rescale() { Dylib::avutil_54.UninitializedFunctionExport( "av_rescale" ); }
void av_rescale_q() { Dylib::avutil_54.UninitializedFunctionExport( "av_rescale_q" ); }
void av_rescale_q_rnd() { Dylib::avutil_54.UninitializedFunctionExport( "av_rescale_q_rnd" ); }
void av_rescale_rnd() { Dylib::avutil_54.UninitializedFunctionExport( "av_rescale_rnd" ); }
void av_sample_fmt_is_planar() { Dylib::avutil_54.UninitializedFunctionExport( "av_sample_fmt_is_planar" ); }
void av_samples_alloc() { Dylib::avutil_54.UninitializedFunctionExport( "av_samples_alloc" ); }
void av_samples_copy() { Dylib::avutil_54.UninitializedFunctionExport( "av_samples_copy" ); }
void av_samples_fill_arrays() { Dylib::avutil_54.UninitializedFunctionExport( "av_samples_fill_arrays" ); }
void av_samples_get_buffer_size() { Dylib::avutil_54.UninitializedFunctionExport( "av_samples_get_buffer_size" ); }
void av_samples_set_silence() { Dylib::avutil_54.UninitializedFunctionExport( "av_samples_set_silence" ); }
void av_set_cpu_flags_mask() { Dylib::avutil_54.UninitializedFunctionExport( "av_set_cpu_flags_mask" ); }
void av_set_options_string() { Dylib::avutil_54.UninitializedFunctionExport( "av_set_options_string" ); }
void av_sha_alloc() { Dylib::avutil_54.UninitializedFunctionExport( "av_sha_alloc" ); }
void av_sha_final() { Dylib::avutil_54.UninitializedFunctionExport( "av_sha_final" ); }
void av_sha_init() { Dylib::avutil_54.UninitializedFunctionExport( "av_sha_init" ); }
void av_sha_update() { Dylib::avutil_54.UninitializedFunctionExport( "av_sha_update" ); }
void av_solve_lls() { Dylib::avutil_54.UninitializedFunctionExport( "av_solve_lls" ); }
void av_stereo3d_alloc() { Dylib::avutil_54.UninitializedFunctionExport( "av_stereo3d_alloc" ); }
void av_stereo3d_create_side_data() { Dylib::avutil_54.UninitializedFunctionExport( "av_stereo3d_create_side_data" ); }
void av_strcasecmp() { Dylib::avutil_54.UninitializedFunctionExport( "av_strcasecmp" ); }
void av_strdup() { Dylib::avutil_54.UninitializedFunctionExport( "av_strdup" ); }
void av_strerror() { Dylib::avutil_54.UninitializedFunctionExport( "av_strerror" ); }
void av_stristart() { Dylib::avutil_54.UninitializedFunctionExport( "av_stristart" ); }
void av_stristr() { Dylib::avutil_54.UninitializedFunctionExport( "av_stristr" ); }
void av_strlcat() { Dylib::avutil_54.UninitializedFunctionExport( "av_strlcat" ); }
void av_strlcatf() { Dylib::avutil_54.UninitializedFunctionExport( "av_strlcatf" ); }
void av_strlcpy() { Dylib::avutil_54.UninitializedFunctionExport( "av_strlcpy" ); }
void av_strncasecmp() { Dylib::avutil_54.UninitializedFunctionExport( "av_strncasecmp" ); }
void av_strndup() { Dylib::avutil_54.UninitializedFunctionExport( "av_strndup" ); }
void av_strnstr() { Dylib::avutil_54.UninitializedFunctionExport( "av_strnstr" ); }
void av_strstart() { Dylib::avutil_54.UninitializedFunctionExport( "av_strstart" ); }
void av_strtod() { Dylib::avutil_54.UninitializedFunctionExport( "av_strtod" ); }
void av_sub_q() { Dylib::avutil_54.UninitializedFunctionExport( "av_sub_q" ); }
void av_timegm() { Dylib::avutil_54.UninitializedFunctionExport( "av_timegm" ); }
void av_tree_destroy() { Dylib::avutil_54.UninitializedFunctionExport( "av_tree_destroy" ); }
void av_tree_enumerate() { Dylib::avutil_54.UninitializedFunctionExport( "av_tree_enumerate" ); }
void av_tree_find() { Dylib::avutil_54.UninitializedFunctionExport( "av_tree_find" ); }
void av_tree_insert() { Dylib::avutil_54.UninitializedFunctionExport( "av_tree_insert" ); }
void av_tree_node_alloc() { Dylib::avutil_54.UninitializedFunctionExport( "av_tree_node_alloc" ); }
void av_update_lls() { Dylib::avutil_54.UninitializedFunctionExport( "av_update_lls" ); }
void av_usleep() { Dylib::avutil_54.UninitializedFunctionExport( "av_usleep" ); }
void av_vlog() { Dylib::avutil_54.UninitializedFunctionExport( "av_vlog" ); }
void av_write_image_line() { Dylib::avutil_54.UninitializedFunctionExport( "av_write_image_line" ); }
void av_xtea_crypt() { Dylib::avutil_54.UninitializedFunctionExport( "av_xtea_crypt" ); }
void av_xtea_init() { Dylib::avutil_54.UninitializedFunctionExport( "av_xtea_init" ); }
void avutil_configuration() { Dylib::avutil_54.UninitializedFunctionExport( "avutil_configuration" ); }
void avutil_license() { Dylib::avutil_54.UninitializedFunctionExport( "avutil_license" ); }
void avutil_version() { Dylib::avutil_54.UninitializedFunctionExport( "avutil_version" ); }
}

namespace {
const Dylib::Import functionImports_[] =
{
  { "av_add_q", (void**)&av_add_q, Dylib::Import::functionStub },
  { "av_adler32_update", (void**)&av_adler32_update, Dylib::Import::functionStub },
  { "av_aes_alloc", (void**)&av_aes_alloc, Dylib::Import::functionStub },
  { "av_aes_crypt", (void**)&av_aes_crypt, Dylib::Import::functionStub },
  { "av_aes_init", (void**)&av_aes_init, Dylib::Import::functionStub },
  { "av_audio_fifo_alloc", (void**)&av_audio_fifo_alloc, Dylib::Import::functionStub },
  { "av_audio_fifo_drain", (void**)&av_audio_fifo_drain, Dylib::Import::functionStub },
  { "av_audio_fifo_free", (void**)&av_audio_fifo_free, Dylib::Import::functionStub },
  { "av_audio_fifo_read", (void**)&av_audio_fifo_read, Dylib::Import::functionStub },
  { "av_audio_fifo_realloc", (void**)&av_audio_fifo_realloc, Dylib::Import::functionStub },
  { "av_audio_fifo_reset", (void**)&av_audio_fifo_reset, Dylib::Import::functionStub },
  { "av_audio_fifo_size", (void**)&av_audio_fifo_size, Dylib::Import::functionStub },
  { "av_audio_fifo_space", (void**)&av_audio_fifo_space, Dylib::Import::functionStub },
  { "av_audio_fifo_write", (void**)&av_audio_fifo_write, Dylib::Import::functionStub },
  { "av_base64_decode", (void**)&av_base64_decode, Dylib::Import::functionStub },
  { "av_base64_encode", (void**)&av_base64_encode, Dylib::Import::functionStub },
  { "av_basename", (void**)&av_basename, Dylib::Import::functionStub },
  { "av_blowfish_crypt", (void**)&av_blowfish_crypt, Dylib::Import::functionStub },
  { "av_blowfish_crypt_ecb", (void**)&av_blowfish_crypt_ecb, Dylib::Import::functionStub },
  { "av_blowfish_init", (void**)&av_blowfish_init, Dylib::Import::functionStub },
  { "av_bmg_get", (void**)&av_bmg_get, Dylib::Import::functionStub },
  { "av_buffer_alloc", (void**)&av_buffer_alloc, Dylib::Import::functionStub },
  { "av_buffer_allocz", (void**)&av_buffer_allocz, Dylib::Import::functionStub },
  { "av_buffer_create", (void**)&av_buffer_create, Dylib::Import::functionStub },
  { "av_buffer_default_free", (void**)&av_buffer_default_free, Dylib::Import::functionStub },
  { "av_buffer_is_writable", (void**)&av_buffer_is_writable, Dylib::Import::functionStub },
  { "av_buffer_make_writable", (void**)&av_buffer_make_writable, Dylib::Import::functionStub },
  { "av_buffer_pool_get", (void**)&av_buffer_pool_get, Dylib::Import::functionStub },
  { "av_buffer_pool_init", (void**)&av_buffer_pool_init, Dylib::Import::functionStub },
  { "av_buffer_pool_uninit", (void**)&av_buffer_pool_uninit, Dylib::Import::functionStub },
  { "av_buffer_realloc", (void**)&av_buffer_realloc, Dylib::Import::functionStub },
  { "av_buffer_ref", (void**)&av_buffer_ref, Dylib::Import::functionStub },
  { "av_buffer_unref", (void**)&av_buffer_unref, Dylib::Import::functionStub },
  { "av_channel_layout_extract_channel", (void**)&av_channel_layout_extract_channel, Dylib::Import::functionStub },
  { "av_compare_mod", (void**)&av_compare_mod, Dylib::Import::functionStub },
  { "av_compare_ts", (void**)&av_compare_ts, Dylib::Import::functionStub },
  { "av_cpu_count", (void**)&av_cpu_count, Dylib::Import::functionStub },
  { "av_crc", (void**)&av_crc, Dylib::Import::functionStub },
  { "av_crc_get_table", (void**)&av_crc_get_table, Dylib::Import::functionStub },
  { "av_crc_init", (void**)&av_crc_init, Dylib::Import::functionStub },
  { "av_ctz", (void**)&av_ctz, Dylib::Import::functionStub },
  { "av_d2q", (void**)&av_d2q, Dylib::Import::functionStub },
  { "av_d2str", (void**)&av_d2str, Dylib::Import::functionStub },
  { "av_default_item_name", (void**)&av_default_item_name, Dylib::Import::functionStub },
  { "av_des_crypt", (void**)&av_des_crypt, Dylib::Import::functionStub },
  { "av_des_init", (void**)&av_des_init, Dylib::Import::functionStub },
  { "av_des_mac", (void**)&av_des_mac, Dylib::Import::functionStub },
  { "av_dict_copy", (void**)&av_dict_copy, Dylib::Import::functionStub },
  { "av_dict_count", (void**)&av_dict_count, Dylib::Import::functionStub },
  { "av_dict_free", (void**)&av_dict_free, Dylib::Import::functionStub },
  { "av_dict_get", (void**)&av_dict_get, Dylib::Import::functionStub },
  { "av_dict_parse_string", (void**)&av_dict_parse_string, Dylib::Import::functionStub },
  { "av_dict_set", (void**)&av_dict_set, Dylib::Import::functionStub },
  { "av_dirname", (void**)&av_dirname, Dylib::Import::functionStub },
  { "av_display_matrix_flip", (void**)&av_display_matrix_flip, Dylib::Import::functionStub },
  { "av_display_rotation_get", (void**)&av_display_rotation_get, Dylib::Import::functionStub },
  { "av_display_rotation_set", (void**)&av_display_rotation_set, Dylib::Import::functionStub },
  { "av_div_q", (void**)&av_div_q, Dylib::Import::functionStub },
  { "av_downmix_info_update_side_data", (void**)&av_downmix_info_update_side_data, Dylib::Import::functionStub },
  { "av_evaluate_lls", (void**)&av_evaluate_lls, Dylib::Import::functionStub },
  { "av_expr_eval", (void**)&av_expr_eval, Dylib::Import::functionStub },
  { "av_expr_free", (void**)&av_expr_free, Dylib::Import::functionStub },
  { "av_expr_parse", (void**)&av_expr_parse, Dylib::Import::functionStub },
  { "av_expr_parse_and_eval", (void**)&av_expr_parse_and_eval, Dylib::Import::functionStub },
  { "av_fast_malloc", (void**)&av_fast_malloc, Dylib::Import::functionStub },
  { "av_fast_realloc", (void**)&av_fast_realloc, Dylib::Import::functionStub },
  { "av_fifo_alloc", (void**)&av_fifo_alloc, Dylib::Import::functionStub },
  { "av_fifo_drain", (void**)&av_fifo_drain, Dylib::Import::functionStub },
  { "av_fifo_free", (void**)&av_fifo_free, Dylib::Import::functionStub },
  { "av_fifo_generic_read", (void**)&av_fifo_generic_read, Dylib::Import::functionStub },
  { "av_fifo_generic_write", (void**)&av_fifo_generic_write, Dylib::Import::functionStub },
  { "av_fifo_realloc2", (void**)&av_fifo_realloc2, Dylib::Import::functionStub },
  { "av_fifo_reset", (void**)&av_fifo_reset, Dylib::Import::functionStub },
  { "av_fifo_size", (void**)&av_fifo_size, Dylib::Import::functionStub },
  { "av_fifo_space", (void**)&av_fifo_space, Dylib::Import::functionStub },
  { "av_file_map", (void**)&av_file_map, Dylib::Import::functionStub },
  { "av_file_unmap", (void**)&av_file_unmap, Dylib::Import::functionStub },
  { "av_find_info_tag", (void**)&av_find_info_tag, Dylib::Import::functionStub },
  { "av_find_nearest_q_idx", (void**)&av_find_nearest_q_idx, Dylib::Import::functionStub },
  { "av_frame_alloc", (void**)&av_frame_alloc, Dylib::Import::functionStub },
  { "av_frame_clone", (void**)&av_frame_clone, Dylib::Import::functionStub },
  { "av_frame_copy", (void**)&av_frame_copy, Dylib::Import::functionStub },
  { "av_frame_copy_props", (void**)&av_frame_copy_props, Dylib::Import::functionStub },
  { "av_frame_free", (void**)&av_frame_free, Dylib::Import::functionStub },
  { "av_frame_get_buffer", (void**)&av_frame_get_buffer, Dylib::Import::functionStub },
  { "av_frame_get_plane_buffer", (void**)&av_frame_get_plane_buffer, Dylib::Import::functionStub },
  { "av_frame_get_side_data", (void**)&av_frame_get_side_data, Dylib::Import::functionStub },
  { "av_frame_is_writable", (void**)&av_frame_is_writable, Dylib::Import::functionStub },
  { "av_frame_make_writable", (void**)&av_frame_make_writable, Dylib::Import::functionStub },
  { "av_frame_move_ref", (void**)&av_frame_move_ref, Dylib::Import::functionStub },
  { "av_frame_new_side_data", (void**)&av_frame_new_side_data, Dylib::Import::functionStub },
  { "av_frame_ref", (void**)&av_frame_ref, Dylib::Import::functionStub },
  { "av_frame_remove_side_data", (void**)&av_frame_remove_side_data, Dylib::Import::functionStub },
  { "av_frame_unref", (void**)&av_frame_unref, Dylib::Import::functionStub },
  { "av_free", (void**)&av_free, Dylib::Import::functionStub },
  { "av_freep", (void**)&av_freep, Dylib::Import::functionStub },
  { "av_gcd", (void**)&av_gcd, Dylib::Import::functionStub },
  { "av_get_bits_per_pixel", (void**)&av_get_bits_per_pixel, Dylib::Import::functionStub },
  { "av_get_bytes_per_sample", (void**)&av_get_bytes_per_sample, Dylib::Import::functionStub },
  { "av_get_channel_layout", (void**)&av_get_channel_layout, Dylib::Import::functionStub },
  { "av_get_channel_layout_channel_index", (void**)&av_get_channel_layout_channel_index, Dylib::Import::functionStub },
  { "av_get_channel_layout_nb_channels", (void**)&av_get_channel_layout_nb_channels, Dylib::Import::functionStub },
  { "av_get_channel_layout_string", (void**)&av_get_channel_layout_string, Dylib::Import::functionStub },
  { "av_get_channel_name", (void**)&av_get_channel_name, Dylib::Import::functionStub },
  { "av_get_cpu_flags", (void**)&av_get_cpu_flags, Dylib::Import::functionStub },
  { "av_get_default_channel_layout", (void**)&av_get_default_channel_layout, Dylib::Import::functionStub },
  { "av_get_packed_sample_fmt", (void**)&av_get_packed_sample_fmt, Dylib::Import::functionStub },
  { "av_get_picture_type_char", (void**)&av_get_picture_type_char, Dylib::Import::functionStub },
  { "av_get_pix_fmt", (void**)&av_get_pix_fmt, Dylib::Import::functionStub },
  { "av_get_pix_fmt_name", (void**)&av_get_pix_fmt_name, Dylib::Import::functionStub },
  { "av_get_pix_fmt_string", (void**)&av_get_pix_fmt_string, Dylib::Import::functionStub },
  { "av_get_planar_sample_fmt", (void**)&av_get_planar_sample_fmt, Dylib::Import::functionStub },
  { "av_get_random_seed", (void**)&av_get_random_seed, Dylib::Import::functionStub },
  { "av_get_sample_fmt", (void**)&av_get_sample_fmt, Dylib::Import::functionStub },
  { "av_get_sample_fmt_name", (void**)&av_get_sample_fmt_name, Dylib::Import::functionStub },
  { "av_get_sample_fmt_string", (void**)&av_get_sample_fmt_string, Dylib::Import::functionStub },
  { "av_get_time_base_q", (void**)&av_get_time_base_q, Dylib::Import::functionStub },
  { "av_get_token", (void**)&av_get_token, Dylib::Import::functionStub },
  { "av_gettime", (void**)&av_gettime, Dylib::Import::functionStub },
  { "av_hmac_alloc", (void**)&av_hmac_alloc, Dylib::Import::functionStub },
  { "av_hmac_calc", (void**)&av_hmac_calc, Dylib::Import::functionStub },
  { "av_hmac_final", (void**)&av_hmac_final, Dylib::Import::functionStub },
  { "av_hmac_free", (void**)&av_hmac_free, Dylib::Import::functionStub },
  { "av_hmac_init", (void**)&av_hmac_init, Dylib::Import::functionStub },
  { "av_hmac_update", (void**)&av_hmac_update, Dylib::Import::functionStub },
  { "av_image_alloc", (void**)&av_image_alloc, Dylib::Import::functionStub },
  { "av_image_check_sar", (void**)&av_image_check_sar, Dylib::Import::functionStub },
  { "av_image_check_size", (void**)&av_image_check_size, Dylib::Import::functionStub },
  { "av_image_copy", (void**)&av_image_copy, Dylib::Import::functionStub },
  { "av_image_copy_plane", (void**)&av_image_copy_plane, Dylib::Import::functionStub },
  { "av_image_fill_linesizes", (void**)&av_image_fill_linesizes, Dylib::Import::functionStub },
  { "av_image_fill_max_pixsteps", (void**)&av_image_fill_max_pixsteps, Dylib::Import::functionStub },
  { "av_image_fill_pointers", (void**)&av_image_fill_pointers, Dylib::Import::functionStub },
  { "av_image_get_linesize", (void**)&av_image_get_linesize, Dylib::Import::functionStub },
  { "av_init_lls", (void**)&av_init_lls, Dylib::Import::functionStub },
  { "av_isdigit", (void**)&av_isdigit, Dylib::Import::functionStub },
  { "av_isgraph", (void**)&av_isgraph, Dylib::Import::functionStub },
  { "av_isspace", (void**)&av_isspace, Dylib::Import::functionStub },
  { "av_isxdigit", (void**)&av_isxdigit, Dylib::Import::functionStub },
  { "av_lfg_init", (void**)&av_lfg_init, Dylib::Import::functionStub },
  { "av_log", (void**)&av_log, Dylib::Import::functionStub },
  { "av_log2", (void**)&av_log2, Dylib::Import::functionStub },
  { "av_log2_16bit", (void**)&av_log2_16bit, Dylib::Import::functionStub },
  { "av_log_default_callback", (void**)&av_log_default_callback, Dylib::Import::functionStub },
  { "av_log_get_level", (void**)&av_log_get_level, Dylib::Import::functionStub },
  { "av_log_set_callback", (void**)&av_log_set_callback, Dylib::Import::functionStub },
  { "av_log_set_flags", (void**)&av_log_set_flags, Dylib::Import::functionStub },
  { "av_log_set_level", (void**)&av_log_set_level, Dylib::Import::functionStub },
  { "av_lzo1x_decode", (void**)&av_lzo1x_decode, Dylib::Import::functionStub },
  { "av_malloc", (void**)&av_malloc, Dylib::Import::functionStub },
  { "av_mallocz", (void**)&av_mallocz, Dylib::Import::functionStub },
  { "av_match_name", (void**)&av_match_name, Dylib::Import::functionStub },
  { "av_md5_alloc", (void**)&av_md5_alloc, Dylib::Import::functionStub },
  { "av_md5_final", (void**)&av_md5_final, Dylib::Import::functionStub },
  { "av_md5_init", (void**)&av_md5_init, Dylib::Import::functionStub },
  { "av_md5_sum", (void**)&av_md5_sum, Dylib::Import::functionStub },
  { "av_md5_update", (void**)&av_md5_update, Dylib::Import::functionStub },
  { "av_memcpy_backptr", (void**)&av_memcpy_backptr, Dylib::Import::functionStub },
  { "av_mul_q", (void**)&av_mul_q, Dylib::Import::functionStub },
  { "av_nearer_q", (void**)&av_nearer_q, Dylib::Import::functionStub },
  { "av_opt_child_class_next", (void**)&av_opt_child_class_next, Dylib::Import::functionStub },
  { "av_opt_child_next", (void**)&av_opt_child_next, Dylib::Import::functionStub },
  { "av_opt_eval_double", (void**)&av_opt_eval_double, Dylib::Import::functionStub },
  { "av_opt_eval_flags", (void**)&av_opt_eval_flags, Dylib::Import::functionStub },
  { "av_opt_eval_float", (void**)&av_opt_eval_float, Dylib::Import::functionStub },
  { "av_opt_eval_int", (void**)&av_opt_eval_int, Dylib::Import::functionStub },
  { "av_opt_eval_int64", (void**)&av_opt_eval_int64, Dylib::Import::functionStub },
  { "av_opt_eval_q", (void**)&av_opt_eval_q, Dylib::Import::functionStub },
  { "av_opt_find", (void**)&av_opt_find, Dylib::Import::functionStub },
  { "av_opt_find2", (void**)&av_opt_find2, Dylib::Import::functionStub },
  { "av_opt_flag_is_set", (void**)&av_opt_flag_is_set, Dylib::Import::functionStub },
  { "av_opt_free", (void**)&av_opt_free, Dylib::Import::functionStub },
  { "av_opt_get", (void**)&av_opt_get, Dylib::Import::functionStub },
  { "av_opt_get_dict_val", (void**)&av_opt_get_dict_val, Dylib::Import::functionStub },
  { "av_opt_get_double", (void**)&av_opt_get_double, Dylib::Import::functionStub },
  { "av_opt_get_int", (void**)&av_opt_get_int, Dylib::Import::functionStub },
  { "av_opt_get_q", (void**)&av_opt_get_q, Dylib::Import::functionStub },
  { "av_opt_next", (void**)&av_opt_next, Dylib::Import::functionStub },
  { "av_opt_set", (void**)&av_opt_set, Dylib::Import::functionStub },
  { "av_opt_set_bin", (void**)&av_opt_set_bin, Dylib::Import::functionStub },
  { "av_opt_set_defaults", (void**)&av_opt_set_defaults, Dylib::Import::functionStub },
  { "av_opt_set_dict", (void**)&av_opt_set_dict, Dylib::Import::functionStub },
  { "av_opt_set_dict_val", (void**)&av_opt_set_dict_val, Dylib::Import::functionStub },
  { "av_opt_set_double", (void**)&av_opt_set_double, Dylib::Import::functionStub },
  { "av_opt_set_int", (void**)&av_opt_set_int, Dylib::Import::functionStub },
  { "av_opt_set_q", (void**)&av_opt_set_q, Dylib::Import::functionStub },
  { "av_opt_show2", (void**)&av_opt_show2, Dylib::Import::functionStub },
  { "av_parse_color", (void**)&av_parse_color, Dylib::Import::functionStub },
  { "av_parse_cpu_flags", (void**)&av_parse_cpu_flags, Dylib::Import::functionStub },
  { "av_parse_time", (void**)&av_parse_time, Dylib::Import::functionStub },
  { "av_parse_video_rate", (void**)&av_parse_video_rate, Dylib::Import::functionStub },
  { "av_parse_video_size", (void**)&av_parse_video_size, Dylib::Import::functionStub },
  { "av_pix_fmt_count_planes", (void**)&av_pix_fmt_count_planes, Dylib::Import::functionStub },
  { "av_pix_fmt_desc_get", (void**)&av_pix_fmt_desc_get, Dylib::Import::functionStub },
  { "av_pix_fmt_desc_get_id", (void**)&av_pix_fmt_desc_get_id, Dylib::Import::functionStub },
  { "av_pix_fmt_desc_next", (void**)&av_pix_fmt_desc_next, Dylib::Import::functionStub },
  { "av_pix_fmt_get_chroma_sub_sample", (void**)&av_pix_fmt_get_chroma_sub_sample, Dylib::Import::functionStub },
  { "av_pix_fmt_swap_endianness", (void**)&av_pix_fmt_swap_endianness, Dylib::Import::functionStub },
  { "av_rc4_crypt", (void**)&av_rc4_crypt, Dylib::Import::functionStub },
  { "av_rc4_init", (void**)&av_rc4_init, Dylib::Import::functionStub },
  { "av_read_image_line", (void**)&av_read_image_line, Dylib::Import::functionStub },
  { "av_realloc", (void**)&av_realloc, Dylib::Import::functionStub },
  { "av_realloc_array", (void**)&av_realloc_array, Dylib::Import::functionStub },
  { "av_reallocp", (void**)&av_reallocp, Dylib::Import::functionStub },
  { "av_reallocp_array", (void**)&av_reallocp_array, Dylib::Import::functionStub },
  { "av_reduce", (void**)&av_reduce, Dylib::Import::functionStub },
  { "av_rescale", (void**)&av_rescale, Dylib::Import::functionStub },
  { "av_rescale_q", (void**)&av_rescale_q, Dylib::Import::functionStub },
  { "av_rescale_q_rnd", (void**)&av_rescale_q_rnd, Dylib::Import::functionStub },
  { "av_rescale_rnd", (void**)&av_rescale_rnd, Dylib::Import::functionStub },
  { "av_sample_fmt_is_planar", (void**)&av_sample_fmt_is_planar, Dylib::Import::functionStub },
  { "av_samples_alloc", (void**)&av_samples_alloc, Dylib::Import::functionStub },
  { "av_samples_copy", (void**)&av_samples_copy, Dylib::Import::functionStub },
  { "av_samples_fill_arrays", (void**)&av_samples_fill_arrays, Dylib::Import::functionStub },
  { "av_samples_get_buffer_size", (void**)&av_samples_get_buffer_size, Dylib::Import::functionStub },
  { "av_samples_set_silence", (void**)&av_samples_set_silence, Dylib::Import::functionStub },
  { "av_set_cpu_flags_mask", (void**)&av_set_cpu_flags_mask, Dylib::Import::functionStub },
  { "av_set_options_string", (void**)&av_set_options_string, Dylib::Import::functionStub },
  { "av_sha_alloc", (void**)&av_sha_alloc, Dylib::Import::functionStub },
  { "av_sha_final", (void**)&av_sha_final, Dylib::Import::functionStub },
  { "av_sha_init", (void**)&av_sha_init, Dylib::Import::functionStub },
  { "av_sha_update", (void**)&av_sha_update, Dylib::Import::functionStub },
  { "av_solve_lls", (void**)&av_solve_lls, Dylib::Import::functionStub },
  { "av_stereo3d_alloc", (void**)&av_stereo3d_alloc, Dylib::Import::functionStub },
  { "av_stereo3d_create_side_data", (void**)&av_stereo3d_create_side_data, Dylib::Import::functionStub },
  { "av_strcasecmp", (void**)&av_strcasecmp, Dylib::Import::functionStub },
  { "av_strdup", (void**)&av_strdup, Dylib::Import::functionStub },
  { "av_strerror", (void**)&av_strerror, Dylib::Import::functionStub },
  { "av_stristart", (void**)&av_stristart, Dylib::Import::functionStub },
  { "av_stristr", (void**)&av_stristr, Dylib::Import::functionStub },
  { "av_strlcat", (void**)&av_strlcat, Dylib::Import::functionStub },
  { "av_strlcatf", (void**)&av_strlcatf, Dylib::Import::functionStub },
  { "av_strlcpy", (void**)&av_strlcpy, Dylib::Import::functionStub },
  { "av_strncasecmp", (void**)&av_strncasecmp, Dylib::Import::functionStub },
  { "av_strndup", (void**)&av_strndup, Dylib::Import::functionStub },
  { "av_strnstr", (void**)&av_strnstr, Dylib::Import::functionStub },
  { "av_strstart", (void**)&av_strstart, Dylib::Import::functionStub },
  { "av_strtod", (void**)&av_strtod, Dylib::Import::functionStub },
  { "av_sub_q", (void**)&av_sub_q, Dylib::Import::functionStub },
  { "av_timegm", (void**)&av_timegm, Dylib::Import::functionStub },
  { "av_tree_destroy", (void**)&av_tree_destroy, Dylib::Import::functionStub },
  { "av_tree_enumerate", (void**)&av_tree_enumerate, Dylib::Import::functionStub },
  { "av_tree_find", (void**)&av_tree_find, Dylib::Import::functionStub },
  { "av_tree_insert", (void**)&av_tree_insert, Dylib::Import::functionStub },
  { "av_tree_node_alloc", (void**)&av_tree_node_alloc, Dylib::Import::functionStub },
  { "av_update_lls", (void**)&av_update_lls, Dylib::Import::functionStub },
  { "av_usleep", (void**)&av_usleep, Dylib::Import::functionStub },
  { "av_vlog", (void**)&av_vlog, Dylib::Import::functionStub },
  { "av_write_image_line", (void**)&av_write_image_line, Dylib::Import::functionStub },
  { "av_xtea_crypt", (void**)&av_xtea_crypt, Dylib::Import::functionStub },
  { "av_xtea_init", (void**)&av_xtea_init, Dylib::Import::functionStub },
  { "avutil_configuration", (void**)&avutil_configuration, Dylib::Import::functionStub },
  { "avutil_license", (void**)&avutil_license, Dylib::Import::functionStub },
  { "avutil_version", (void**)&avutil_version, Dylib::Import::functionStub },
  { 0, 0, 0 }
};
const Dylib::Import* functionImports = functionImports_;
}

#endif // STATIC_LIBAVUTIL_54

