// Import declarations for swscale-3 library
// generated by C:\BCI2000.svn\build\buildutils\create_import_table.exe from win32-x86/dynamic/swscale-3.dll
#if STATIC_LIBSWSCALE_3

namespace Dylib { bool swscale_3_Loaded() { return true; } }
extern "C" {
void* p_sws_context_class = &sws_context_class;
}

#else

#include "DylibImports.h"
namespace { extern const Dylib::Import* functionImports; }

// Here you may specify a custom error message to be displayed when the library cannot be found.
static const char* notFoundMsg = "";
// Here you may specify an URL to some local or remote help resource.
static const char* notFoundURL = "";
RegisterDylibWithAliases( swscale_3, "swscale-3", functionImports, notFoundMsg, notFoundURL );

extern "C" {
void* p_sws_context_class = Dylib::swscale_3.ResolveDataExport( "sws_context_class" );

// NOTE: When loading the library, function bodies will be overwritten with absolute jumps
// to imported functions, i.e. function bodies must be roughly 2 * sizeof(void*) bytes long.
// A call to a member function with a pointer argument should be large enough.
// 
// In addition, having distinct function bodies for each function stub
// is important -- that makes it impossible for size optimizers to
// collapse them into a single definition.
//
void sws_addVec() { Dylib::swscale_3.UninitializedFunctionExport( "sws_addVec" ); }
void sws_allocVec() { Dylib::swscale_3.UninitializedFunctionExport( "sws_allocVec" ); }
void sws_alloc_context() { Dylib::swscale_3.UninitializedFunctionExport( "sws_alloc_context" ); }
void sws_cloneVec() { Dylib::swscale_3.UninitializedFunctionExport( "sws_cloneVec" ); }
void sws_convVec() { Dylib::swscale_3.UninitializedFunctionExport( "sws_convVec" ); }
void sws_convertPalette8ToPacked24() { Dylib::swscale_3.UninitializedFunctionExport( "sws_convertPalette8ToPacked24" ); }
void sws_convertPalette8ToPacked32() { Dylib::swscale_3.UninitializedFunctionExport( "sws_convertPalette8ToPacked32" ); }
void sws_format_name() { Dylib::swscale_3.UninitializedFunctionExport( "sws_format_name" ); }
void sws_freeContext() { Dylib::swscale_3.UninitializedFunctionExport( "sws_freeContext" ); }
void sws_freeFilter() { Dylib::swscale_3.UninitializedFunctionExport( "sws_freeFilter" ); }
void sws_freeVec() { Dylib::swscale_3.UninitializedFunctionExport( "sws_freeVec" ); }
void sws_getCachedContext() { Dylib::swscale_3.UninitializedFunctionExport( "sws_getCachedContext" ); }
void sws_getCoefficients() { Dylib::swscale_3.UninitializedFunctionExport( "sws_getCoefficients" ); }
void sws_getColorspaceDetails() { Dylib::swscale_3.UninitializedFunctionExport( "sws_getColorspaceDetails" ); }
void sws_getConstVec() { Dylib::swscale_3.UninitializedFunctionExport( "sws_getConstVec" ); }
void sws_getContext() { Dylib::swscale_3.UninitializedFunctionExport( "sws_getContext" ); }
void sws_getDefaultFilter() { Dylib::swscale_3.UninitializedFunctionExport( "sws_getDefaultFilter" ); }
void sws_getGaussianVec() { Dylib::swscale_3.UninitializedFunctionExport( "sws_getGaussianVec" ); }
void sws_getIdentityVec() { Dylib::swscale_3.UninitializedFunctionExport( "sws_getIdentityVec" ); }
void sws_get_class() { Dylib::swscale_3.UninitializedFunctionExport( "sws_get_class" ); }
void sws_init_context() { Dylib::swscale_3.UninitializedFunctionExport( "sws_init_context" ); }
void sws_isSupportedEndiannessConversion() { Dylib::swscale_3.UninitializedFunctionExport( "sws_isSupportedEndiannessConversion" ); }
void sws_isSupportedInput() { Dylib::swscale_3.UninitializedFunctionExport( "sws_isSupportedInput" ); }
void sws_isSupportedOutput() { Dylib::swscale_3.UninitializedFunctionExport( "sws_isSupportedOutput" ); }
void sws_normalizeVec() { Dylib::swscale_3.UninitializedFunctionExport( "sws_normalizeVec" ); }
void sws_printVec2() { Dylib::swscale_3.UninitializedFunctionExport( "sws_printVec2" ); }
void sws_rgb2rgb_init() { Dylib::swscale_3.UninitializedFunctionExport( "sws_rgb2rgb_init" ); }
void sws_scale() { Dylib::swscale_3.UninitializedFunctionExport( "sws_scale" ); }
void sws_scaleVec() { Dylib::swscale_3.UninitializedFunctionExport( "sws_scaleVec" ); }
void sws_setColorspaceDetails() { Dylib::swscale_3.UninitializedFunctionExport( "sws_setColorspaceDetails" ); }
void sws_shiftVec() { Dylib::swscale_3.UninitializedFunctionExport( "sws_shiftVec" ); }
void sws_subVec() { Dylib::swscale_3.UninitializedFunctionExport( "sws_subVec" ); }
void swscale_configuration() { Dylib::swscale_3.UninitializedFunctionExport( "swscale_configuration" ); }
void swscale_license() { Dylib::swscale_3.UninitializedFunctionExport( "swscale_license" ); }
void swscale_version() { Dylib::swscale_3.UninitializedFunctionExport( "swscale_version" ); }
}

namespace {
const Dylib::Import functionImports_[] =
{
  { "sws_addVec", (void**)&sws_addVec, Dylib::Import::functionStub },
  { "sws_allocVec", (void**)&sws_allocVec, Dylib::Import::functionStub },
  { "sws_alloc_context", (void**)&sws_alloc_context, Dylib::Import::functionStub },
  { "sws_cloneVec", (void**)&sws_cloneVec, Dylib::Import::functionStub },
  { "sws_convVec", (void**)&sws_convVec, Dylib::Import::functionStub },
  { "sws_convertPalette8ToPacked24", (void**)&sws_convertPalette8ToPacked24, Dylib::Import::functionStub },
  { "sws_convertPalette8ToPacked32", (void**)&sws_convertPalette8ToPacked32, Dylib::Import::functionStub },
  { "sws_format_name", (void**)&sws_format_name, Dylib::Import::functionStub },
  { "sws_freeContext", (void**)&sws_freeContext, Dylib::Import::functionStub },
  { "sws_freeFilter", (void**)&sws_freeFilter, Dylib::Import::functionStub },
  { "sws_freeVec", (void**)&sws_freeVec, Dylib::Import::functionStub },
  { "sws_getCachedContext", (void**)&sws_getCachedContext, Dylib::Import::functionStub },
  { "sws_getCoefficients", (void**)&sws_getCoefficients, Dylib::Import::functionStub },
  { "sws_getColorspaceDetails", (void**)&sws_getColorspaceDetails, Dylib::Import::functionStub },
  { "sws_getConstVec", (void**)&sws_getConstVec, Dylib::Import::functionStub },
  { "sws_getContext", (void**)&sws_getContext, Dylib::Import::functionStub },
  { "sws_getDefaultFilter", (void**)&sws_getDefaultFilter, Dylib::Import::functionStub },
  { "sws_getGaussianVec", (void**)&sws_getGaussianVec, Dylib::Import::functionStub },
  { "sws_getIdentityVec", (void**)&sws_getIdentityVec, Dylib::Import::functionStub },
  { "sws_get_class", (void**)&sws_get_class, Dylib::Import::functionStub },
  { "sws_init_context", (void**)&sws_init_context, Dylib::Import::functionStub },
  { "sws_isSupportedEndiannessConversion", (void**)&sws_isSupportedEndiannessConversion, Dylib::Import::functionStub },
  { "sws_isSupportedInput", (void**)&sws_isSupportedInput, Dylib::Import::functionStub },
  { "sws_isSupportedOutput", (void**)&sws_isSupportedOutput, Dylib::Import::functionStub },
  { "sws_normalizeVec", (void**)&sws_normalizeVec, Dylib::Import::functionStub },
  { "sws_printVec2", (void**)&sws_printVec2, Dylib::Import::functionStub },
  { "sws_rgb2rgb_init", (void**)&sws_rgb2rgb_init, Dylib::Import::functionStub },
  { "sws_scale", (void**)&sws_scale, Dylib::Import::functionStub },
  { "sws_scaleVec", (void**)&sws_scaleVec, Dylib::Import::functionStub },
  { "sws_setColorspaceDetails", (void**)&sws_setColorspaceDetails, Dylib::Import::functionStub },
  { "sws_shiftVec", (void**)&sws_shiftVec, Dylib::Import::functionStub },
  { "sws_subVec", (void**)&sws_subVec, Dylib::Import::functionStub },
  { "swscale_configuration", (void**)&swscale_configuration, Dylib::Import::functionStub },
  { "swscale_license", (void**)&swscale_license, Dylib::Import::functionStub },
  { "swscale_version", (void**)&swscale_version, Dylib::Import::functionStub },
  { 0, 0, 0 }
};
const Dylib::Import* functionImports = functionImports_;
}

#endif // STATIC_LIBSWSCALE_3

