// Import declarations for fglove library, generated by DylibTool
#ifndef fglove_IMPORTS_H
#define fglove_IMPORTS_H

#include "Win32Defs.h"

// Disable function declarations in the original header
// file by #defining function names to point to symbols that
// are not referenced by any code.
#define fdOpen fdOpen_0c3f__
#define fdClose fdClose_7159__
#define fdGetGloveHand fdGetGloveHand_4b17__
#define fdGetGloveType fdGetGloveType_490e__
#define fdGetNumSensors fdGetNumSensors_5f64__
#define fdGetSensorRawAll fdGetSensorRawAll_4928__
#define fdGetSensorRaw fdGetSensorRaw_4928__ 
#define fdSetSensorRawAll fdSetSensorRawAll_5d28__
#define fdSetSensorRaw fdSetSensorRaw_7201__
#define fdGetSensorScaledAll fdGetSensorScaledAll_3002__
#define fdGetSensorScaled fdGetSensorScaled_0127__
#define fdGetNumGestures fdGetNumGestures_266c__
#define fdGetGesture fdGetGesture_147b__
#define fdGetGestureA fdGetGestureA_2907__
#define fdGetCalibrationAll fdGetCalibrationAll_5b1e__
#define fdGetCalibration fdGetCalibration_6b68__
#define fdSetCalibrationAll fdSetCalibrationAll_4f1e__
#define fdSetCalibration fdSetCalibration_2433__
#define fdResetCalibration fdResetCalibration_1312__
#define fdResetCalibrationAll fdResetCalibrationAll_2364__
#define fdGetSensorMaxAll fdGetSensorMaxAll_0a34__
#define fdGetSensorMax fdGetSensorMax_733d__
#define fdSetSensorMaxAll fdSetSensorMaxAll_1e34__
#define fdSetSensorMax fdSetSensorMax_3d6d__
#define fdGetThresholdAll fdGetThresholdAll_772f__
#define fdGetThreshold fdGetThreshold_4759__
#define fdSetThresholdAll fdSetThresholdAll_632f__
#define fdSetThreshold fdSetThreshold_171d__
#define fdGetGloveInfo fdGetGloveInfo_2564__
#define fdGetDriverInfo fdGetDriverInfo_0b23__
#define fdSetCallback fdSetCallback_4f1c__
#define fdRemoveCallback fdRemoveCallback_4650__
#define fdGetPacketRate fdGetPacketRate_7153__
#define fdNewData fdNewData_117e__
#define fdGetFWVersionMajor fdGetFWVersionMajor_7048__
#define fdGetFWVersionMinor fdGetFWVersionMinor_7440__
#define fdGetAutoCalibrate fdGetAutoCalibrate_0e33__
#define fdSetAutoCalibrate fdSetAutoCalibrate_4041__
#define fdSaveCalibration fdSaveCalibration_2e6c__
#define fdLoadCalibration fdLoadCalibration_2663__
#define fdScanUSB fdScanUSB_693a__
#define fdGetSerialNumber fdGetSerialNumber_131b__

#include "fglove.h"

// Use #undef to restore function names before declaring
// function pointers with the names originally used to
// declare imports.
#undef fdOpen
#undef fdClose
#undef fdGetGloveHand
#undef fdGetGloveType
#undef fdGetNumSensors
#undef fdGetSensorRawAll
#undef fdGetSensorRaw
#undef fdSetSensorRawAll
#undef fdSetSensorRaw
#undef fdGetSensorScaledAll
#undef fdGetSensorScaled
#undef fdGetNumGestures
#undef fdGetGesture
#undef fdGetGestureA
#undef fdGetCalibrationAll
#undef fdGetCalibration
#undef fdSetCalibrationAll
#undef fdSetCalibration
#undef fdResetCalibration
#undef fdResetCalibrationAll
#undef fdGetSensorMaxAll
#undef fdGetSensorMax
#undef fdSetSensorMaxAll
#undef fdSetSensorMax
#undef fdGetThresholdAll
#undef fdGetThreshold
#undef fdSetThresholdAll
#undef fdSetThreshold
#undef fdGetGloveInfo
#undef fdGetDriverInfo
#undef fdSetCallback
#undef fdRemoveCallback
#undef fdGetPacketRate
#undef fdNewData
#undef fdGetFWVersionMajor
#undef fdGetFWVersionMinor
#undef fdGetAutoCalibrate
#undef fdSetAutoCalibrate
#undef fdSaveCalibration
#undef fdLoadCalibration
#undef fdScanUSB
#undef fdGetSerialNumber

extern "C" fdGlove* ( *fdOpen)( char* pPort);
extern "C" int ( *fdClose)( fdGlove* pFG);
extern "C" int ( *fdGetGloveHand)( fdGlove* pFG);
extern "C" int ( *fdGetGloveType)( fdGlove* pFG);
extern "C" int ( *fdGetNumSensors)( fdGlove* pFG);
extern "C" void ( *fdGetSensorRawAll)( fdGlove* pFG, unsigned short* pData);
extern "C" unsigned short ( *fdGetSensorRaw)( fdGlove* pFG, int nSensor); 
extern "C" void ( *fdSetSensorRawAll)( fdGlove* pFG, unsigned short* pData);
extern "C" void ( *fdSetSensorRaw)( fdGlove* pFG, int nSensor, unsigned short nRaw);
extern "C" void ( *fdGetSensorScaledAll)( fdGlove* pFG, float* pData);
extern "C" float ( *fdGetSensorScaled)( fdGlove* pFG, int nSensor);
extern "C" int ( *fdGetNumGestures)( fdGlove* pFG);
extern "C" int ( *fdGetGesture)( fdGlove* pFG);
extern "C" int ( *fdGetGestureA)( fdGlove* pFG);
extern "C" void ( *fdGetCalibrationAll)( fdGlove* pFG, unsigned short* pUpper, unsigned short* pLower);
extern "C" void ( *fdGetCalibration)( fdGlove* pFG, int nSensor, unsigned short* pUpper, unsigned short* pLower);
extern "C" void ( *fdSetCalibrationAll)( fdGlove* pFG, unsigned short* pUpper, unsigned short* pLower);
extern "C" void ( *fdSetCalibration)( fdGlove* pFG, int nSensor, unsigned short nUpper, unsigned short nLower);
extern "C" void ( *fdResetCalibration)( fdGlove* pFG, int nSensor);
extern "C" void ( *fdResetCalibrationAll)( fdGlove* pFG);
extern "C" void ( *fdGetSensorMaxAll)( fdGlove* pFG, float* pMax);
extern "C" float ( *fdGetSensorMax)( fdGlove* pFG, int nSensor);
extern "C" void ( *fdSetSensorMaxAll)( fdGlove* pFG, float* pMax);
extern "C" void ( *fdSetSensorMax)( fdGlove* pFG, int nSensor, float fMax);
extern "C" void ( *fdGetThresholdAll)( fdGlove* pFG, float* pUpper, float* pLower);
extern "C" void ( *fdGetThreshold)( fdGlove* pFG, int nSensor, float* pUpper, float* pLower);
extern "C" void ( *fdSetThresholdAll)( fdGlove* pFG, float* pUpper, float* pLower);
extern "C" void ( *fdSetThreshold)( fdGlove* pFG, int nSensor, float fUpper, float fLower);
extern "C" void ( *fdGetGloveInfo)( fdGlove* pFG, unsigned char* pData);
extern "C" void ( *fdGetDriverInfo)( fdGlove* pFG, unsigned char* pData);
extern "C" void ( *fdSetCallback)( fdGlove* pFG, void* pFunc, void* param);
extern "C" void ( *fdRemoveCallback)( fdGlove* pFG);
extern "C" int ( *fdGetPacketRate)( fdGlove* pFG);
extern "C" bool ( *fdNewData)( fdGlove* pFG);
extern "C" int ( *fdGetFWVersionMajor)( fdGlove* pFG);
extern "C" int ( *fdGetFWVersionMinor)( fdGlove* pFG);
extern "C" bool ( *fdGetAutoCalibrate)( fdGlove* pFG);
extern "C" bool ( *fdSetAutoCalibrate)( fdGlove* pFG, bool bAutoCalibrate);
extern "C" bool ( *fdSaveCalibration)( fdGlove* pFG, const char* pFileName);
extern "C" bool ( *fdLoadCalibration)( fdGlove* pFG, const char* pFileName);
extern "C" int ( *fdScanUSB)( unsigned short* aPID, int& nNumMax);
extern "C" bool ( *fdGetSerialNumber)( fdGlove* pFG, char* pData);

namespace Dylib { bool fglove_Loaded(); }

#endif // fglove_IMPORTS_H
