// Import declarations for core library, generated by DylibTool
#include "core.imports.h"
#include "DylibImports.h"

extern "C" { void (__cdecl *tobii_sdk_error_destroy)( tobii_sdk_error_t* error); }
extern "C" { tobii_sdk_error_t* (__cdecl *tobii_sdk_error_clone)( const tobii_sdk_error_t* error); }
extern "C" { const char* (__cdecl *tobii_sdk_error_get_message)( const tobii_sdk_error_t* error); }
extern "C" { tobii_sdk_error_code_t (__cdecl *tobii_sdk_error_get_code)( const tobii_sdk_error_t* error); }
extern "C" { const char* (__cdecl *tobii_sdk_error_to_string)( const tobii_sdk_error_t* error); }
extern "C" { uint32_t (__cdecl *tobii_sdk_error_is_failure)( const tobii_sdk_error_t* error); }
extern "C" { const char* (__cdecl *tobii_sdk_error_convert_code_to_string)( tobii_sdk_error_code_t code); }
extern "C" { tobii_sdk_error_t* (__cdecl *tobii_sdk_error_create_generic)( tobii_sdk_error_code_t code, const char* message); }
extern "C" { tobii_sdk_blob_t* (__cdecl *tobii_sdk_blob_create)( uint32_t size, tobii_sdk_error_t** error); }
extern "C" { uint32_t (__cdecl *tobii_sdk_blob_get_size)( tobii_sdk_blob_t* blob, tobii_sdk_error_t** error); }
extern "C" { uint8_t* (__cdecl *tobii_sdk_blob_get_data)( tobii_sdk_blob_t* blob, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_blob_destroy)( tobii_sdk_blob_t* blob); }
extern "C" { tobii_sdk_mainloop_t* (__cdecl *tobii_sdk_mainloop_create)( tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_mainloop_run)( tobii_sdk_mainloop_t* loop, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_mainloop_quit)( tobii_sdk_mainloop_t* loop, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_mainloop_destroy)( tobii_sdk_mainloop_t* loop); }
extern "C" { uint32_t (__cdecl *tobii_sdk_device_info_iterator_move_next)( tobii_sdk_device_info_iterator_t* iterator, tobii_sdk_error_t** error); }
extern "C" { const char* (__cdecl *tobii_sdk_device_info_iterator_get_key_name)( tobii_sdk_device_info_iterator_t* iterator, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_device_info_iterator_destroy)( tobii_sdk_device_info_iterator_t* iterator); }
extern "C" { tobii_sdk_device_info_t* (__cdecl *tobii_sdk_device_info_clone)( const tobii_sdk_device_info_t* device_info, tobii_sdk_error_t** error); }
extern "C" { tobii_sdk_device_info_t* (__cdecl *tobii_sdk_device_info_create_test)( tobii_sdk_error_t** error); }
extern "C" { const char* (__cdecl *tobii_sdk_device_info_get_product_id)( tobii_sdk_device_info_t* device_info, tobii_sdk_error_t** error); }
extern "C" { const char* (__cdecl *tobii_sdk_device_info_get)( tobii_sdk_device_info_t* device_info, const char* key, tobii_sdk_error_t** error); }
extern "C" { tobii_sdk_device_info_iterator_t* (__cdecl *tobii_sdk_device_info_get_iterator)( tobii_sdk_device_info_t* device_info, tobii_sdk_error_t** error); }
extern "C" { tobii_sdk_factory_info_t* (__cdecl *tobii_sdk_device_info_get_factory_info)( tobii_sdk_device_info_t* device_info, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_device_info_destroy)( tobii_sdk_device_info_t* device_info); }
extern "C" { tobii_sdk_factory_info_t* (__cdecl *tobii_sdk_factory_info_create_for_networked_eyetracker)( const char* ip_address_or_hostname, uint32_t tetserver_port, uint32_t synchronization_port, tobii_sdk_error_t** error); }
extern "C" { const char* (__cdecl *tobii_sdk_factory_info_get_representation)( tobii_sdk_factory_info_t* factory_info, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_factory_info_destroy)( tobii_sdk_factory_info_t* factory_info); }
extern "C" { tobii_sdk_device_browser_t* (__cdecl *tobii_sdk_device_browser_create)( tobii_sdk_mainloop_t* mainloop, tobii_sdk_device_browser_callback_t callback, void* user_data, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_device_browser_destroy)( tobii_sdk_device_browser_t* browser); }
extern "C" { tobii_sdk_device_info_list_t* (__cdecl *tobii_sdk_device_browser_get_device_list)( tobii_sdk_device_browser_t* browser, tobii_sdk_error_t** error); }
extern "C" { uint32_t (__cdecl *tobii_sdk_device_info_list_get_size)( tobii_sdk_device_info_list_t* device_list, tobii_sdk_error_t** error); }
extern "C" { tobii_sdk_device_info_t* (__cdecl *tobii_sdk_device_info_list_get_at_index)( tobii_sdk_device_info_list_t* list, uint32_t index, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_device_info_list_destroy)( tobii_sdk_device_info_list_t* device_list); }
extern "C" { uint32_t (__cdecl *tobii_sdk_vector_type_is_compatible)( tobii_sdk_param_type_t element_type); }
extern "C" { tobii_sdk_vector_t* (__cdecl *tobii_sdk_vector_create)( uint32_t size, tobii_sdk_param_type_t element_type, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_vector_destroy)( tobii_sdk_vector_t* vector); }
extern "C" { tobii_sdk_param_type_t (__cdecl *tobii_sdk_vector_get_element_type)( const tobii_sdk_vector_t* vector, tobii_sdk_error_t** error); }
extern "C" { uint32_t (__cdecl *tobii_sdk_vector_get_length)( const tobii_sdk_vector_t* vector, tobii_sdk_error_t** error); }
extern "C" { int32_t (__cdecl *tobii_sdk_vector_get_int32)( const tobii_sdk_vector_t* vector, uint32_t index, tobii_sdk_error_t** error); }
extern "C" { uint32_t (__cdecl *tobii_sdk_vector_get_uint32)( const tobii_sdk_vector_t* vector, uint32_t index, tobii_sdk_error_t** error); }
extern "C" { float (__cdecl *tobii_sdk_vector_get_fixed_15x16_as_float32)( const tobii_sdk_vector_t* vector, uint32_t index, tobii_sdk_error_t** error); }
extern "C" { double (__cdecl *tobii_sdk_vector_get_fixed_22x41_as_float64)( const tobii_sdk_vector_t* vector, uint32_t index, tobii_sdk_error_t** error); }
extern "C" { const char* (__cdecl *tobii_sdk_vector_get_string)( const tobii_sdk_vector_t* vector, uint32_t index, tobii_sdk_error_t** error); }
extern "C" { uint32_t (__cdecl *tobii_sdk_vector_get_string_length)( const tobii_sdk_vector_t* vector, uint32_t index, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_vector_set_int32)( tobii_sdk_vector_t* vector, uint32_t index, int32_t value, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_vector_set_uint32)( tobii_sdk_vector_t* vector, uint32_t index, uint32_t value, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_vector_set_fixed_15x16_as_float32)( tobii_sdk_vector_t* vector, uint32_t index, float value, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_vector_set_fixed_22x41_as_float64)( tobii_sdk_vector_t* vector, uint32_t index, double value, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_vector_set_string)( tobii_sdk_vector_t* vector, uint32_t index, const char* string, uint32_t length, tobii_sdk_error_t** error); }
extern "C" { tobii_sdk_param_stack_t* (__cdecl *tobii_sdk_param_stack_create)( tobii_sdk_error_t** error); }
extern "C" { tobii_sdk_param_stack_t* (__cdecl *tobii_sdk_param_stack_create_test_stack)( tobii_sdk_error_t** error); }
extern "C" { tobii_sdk_param_stack_t* (__cdecl *tobii_sdk_param_stack_clone)( const tobii_sdk_param_stack_t* param, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_param_stack_destroy)( tobii_sdk_param_stack_t* param); }
extern "C" { uint32_t (__cdecl *tobii_sdk_param_stack_get_size)( const tobii_sdk_param_stack_t* param, tobii_sdk_error_t** error); }
extern "C" { tobii_sdk_param_type_t (__cdecl *tobii_sdk_param_stack_get_type)( const tobii_sdk_param_stack_t* param, uint32_t index, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_param_stack_append)( tobii_sdk_param_stack_t* param_stack, const tobii_sdk_param_stack_t* append, tobii_sdk_error_t** error); }
extern "C" { int32_t (__cdecl *tobii_sdk_param_stack_get_int32)( const tobii_sdk_param_stack_t* params, uint32_t index, tobii_sdk_error_t** error); }
extern "C" { uint32_t (__cdecl *tobii_sdk_param_stack_get_uint32)( const tobii_sdk_param_stack_t* params, uint32_t index, tobii_sdk_error_t** error); }
extern "C" { int64_t (__cdecl *tobii_sdk_param_stack_get_int64)( const tobii_sdk_param_stack_t* params, uint32_t index, tobii_sdk_error_t** error); }
extern "C" { uint64_t (__cdecl *tobii_sdk_param_stack_get_uint64)( const tobii_sdk_param_stack_t* params, uint32_t index, tobii_sdk_error_t** error); }
extern "C" { float (__cdecl *tobii_sdk_param_stack_get_float32)( const tobii_sdk_param_stack_t* params, uint32_t index, tobii_sdk_error_t** error); }
extern "C" { double (__cdecl *tobii_sdk_param_stack_get_float64)( const tobii_sdk_param_stack_t* params, uint32_t index, tobii_sdk_error_t** error); }
extern "C" { float (__cdecl *tobii_sdk_param_stack_get_fixed_15x16_as_float32)( const tobii_sdk_param_stack_t* params, uint32_t index, tobii_sdk_error_t** error); }
extern "C" { double (__cdecl *tobii_sdk_param_stack_get_fixed_22x41_as_float64)( const tobii_sdk_param_stack_t* params, uint32_t index, tobii_sdk_error_t** error); }
extern "C" { uint32_t (__cdecl *tobii_sdk_param_stack_get_node_prolog)( const tobii_sdk_param_stack_t* params, uint32_t index, tobii_sdk_error_t** error); }
extern "C" { const char* (__cdecl *tobii_sdk_param_stack_get_string)( const tobii_sdk_param_stack_t* params, uint32_t index, tobii_sdk_error_t** error); }
extern "C" { uint32_t (__cdecl *tobii_sdk_param_stack_get_string_length)( const tobii_sdk_param_stack_t* params, uint32_t index, tobii_sdk_error_t** error); }
extern "C" { uint32_t (__cdecl *tobii_sdk_param_stack_get_blob_length)( const tobii_sdk_param_stack_t* params, uint32_t index, tobii_sdk_error_t** error); }
extern "C" { tobii_sdk_vector_t* (__cdecl *tobii_sdk_param_stack_get_vector)( const tobii_sdk_param_stack_t* params, uint32_t index, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_param_stack_push_int32)( tobii_sdk_param_stack_t* params, int32_t value, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_param_stack_push_uint32)( tobii_sdk_param_stack_t* params, uint32_t value, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_param_stack_push_int64)( tobii_sdk_param_stack_t* params, int64_t value, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_param_stack_push_uint64)( tobii_sdk_param_stack_t* params, uint64_t value, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_param_stack_push_string)( tobii_sdk_param_stack_t* params, const char* value, const uint32_t length, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_param_stack_push_float32_as_fixed_15x16)( tobii_sdk_param_stack_t* params, float value, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_param_stack_push_float64_as_fixed_22x41)( tobii_sdk_param_stack_t* params, double value, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_param_stack_push_node_prolog)( tobii_sdk_param_stack_t* params, uint32_t value, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_param_stack_push_float32)( tobii_sdk_param_stack_t* params, float value, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_param_stack_push_float64)( tobii_sdk_param_stack_t* params, double value, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_param_stack_push_blob)( tobii_sdk_param_stack_t* params, const unsigned char* blob, const uint32_t length, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_param_stack_push_vector)( tobii_sdk_param_stack_t* params, const tobii_sdk_vector_t* vector, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_callback_connection_destroy)( tobii_sdk_callback_connection_t* callback_connection); }
extern "C" { void (__cdecl *tobii_sdk_message_passer_get)( tobii_sdk_factory_info_t* factory_info, tobii_sdk_mainloop_t* loop, tobii_sdk_message_passer_get_handler_t handler, void* handler_user_data, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_message_passer_destroy)( tobii_sdk_message_passer_t* mpi); }
extern "C" { void (__cdecl *tobii_sdk_message_passer_enable_nop_sending)( tobii_sdk_message_passer_t* mpi, tobii_sdk_opcode_t opcode, const tobii_sdk_param_stack_t* params, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_message_passer_disable_nop_sending)( tobii_sdk_message_passer_t* mpi, tobii_sdk_error_t** error); }
extern "C" { uint32_t (__cdecl *tobii_sdk_message_passer_execute_request)( tobii_sdk_message_passer_t* mpi, tobii_sdk_opcode_t opcode, const tobii_sdk_param_stack_t* params, tobii_sdk_response_handler_t response_handler, void* response_user_data, tobii_sdk_error_t** error); }
extern "C" { tobii_sdk_callback_connection_t* (__cdecl *tobii_sdk_message_passer_add_data_handler)( tobii_sdk_message_passer_t* mpi, tobii_sdk_opcode_t opcode, tobii_sdk_data_handler_t data_handler, void* user_data, tobii_sdk_error_t** error); }
extern "C" { tobii_sdk_callback_connection_t* (__cdecl *tobii_sdk_message_passer_add_error_handler)( tobii_sdk_message_passer_t* mpi, tobii_sdk_error_handler_t error_handler, void* user_data, tobii_sdk_error_t** error); }
extern "C" { tobii_sdk_clock_t* (__cdecl *tobii_sdk_clock_get_default)( tobii_sdk_error_t** error); }
extern "C" { tobii_sdk_clock_t* (__cdecl *tobii_sdk_clock_create_user_defined)( tobii_sdk_clock_get_time_fn_t time_func, tobii_sdk_clock_get_resolution_fn_t res_func, tobii_sdk_clock_destroy_fn_t destructor, void* instance_data, tobii_sdk_error_t** error); }
extern "C" { int64_t (__cdecl *tobii_sdk_clock_get_time)( tobii_sdk_clock_t* clock, tobii_sdk_error_t** error); }
extern "C" { int64_t (__cdecl *tobii_sdk_clock_get_resolution)( tobii_sdk_clock_t* clock, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_clock_destroy)( tobii_sdk_clock_t* clock); }
extern "C" { tobii_sdk_sync_state_t* (__cdecl *tobii_sdk_sync_state_clone)( const tobii_sdk_sync_state_t* state, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_sync_state_destroy)( tobii_sdk_sync_state_t* state); }
extern "C" { tobii_sdk_sync_state_flag_t (__cdecl *tobii_sdk_sync_state_get_sync_state_flag)( const tobii_sdk_sync_state_t* state, tobii_sdk_error_t** error); }
extern "C" { uint32_t (__cdecl *tobii_sdk_sync_state_get_number_of_points_in_use)( const tobii_sdk_sync_state_t* state, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_sync_state_get_point_in_use)( const tobii_sdk_sync_state_t* state, uint32_t index, int64_t* local_midpoint, int64_t* remote, int64_t* roundtrip, tobii_sdk_error_t** error); }
extern "C" { int64_t (__cdecl *tobii_sdk_sync_state_get_error_approximation)( const tobii_sdk_sync_state_t* state, tobii_sdk_error_t** error); }
extern "C" { tobii_sdk_sync_manager_t* (__cdecl *tobii_sdk_sync_manager_create)( tobii_sdk_clock_t* clock, tobii_sdk_factory_info_t* factory_info, tobii_sdk_mainloop_t* loop, tobii_sdk_sync_manager_error_handler_t error_handler, void* error_handler_user_data, tobii_sdk_sync_manager_status_changed_handler_t status_handler, void* status_changed_user_data, tobii_sdk_error_t** error); }
extern "C" { int64_t (__cdecl *tobii_sdk_sync_manager_convert_from_local_to_remote)( const tobii_sdk_sync_manager_t* sync_manager, int64_t local, tobii_sdk_error_t** error); }
extern "C" { int64_t (__cdecl *tobii_sdk_sync_manager_convert_from_remote_to_local)( const tobii_sdk_sync_manager_t* sync_manager, int64_t remote, tobii_sdk_error_t** error); }
extern "C" { tobii_sdk_sync_state_t* (__cdecl *tobii_sdk_sync_manager_get_sync_state)( const tobii_sdk_sync_manager_t* sync_manager, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_sync_manager_destroy)( tobii_sdk_sync_manager_t* sync_manager); }
extern "C" { tobii_sdk_upgrade_package_t* (__cdecl *tobii_sdk_upgrade_package_create)( tobii_sdk_error_t** error); }
extern "C" { tobii_sdk_upgrade_package_t* (__cdecl *tobii_sdk_upgrade_package_parse)( const void* package, uint32_t package_size, uint32_t allow_unknown_parts, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_upgrade_package_destroy)( tobii_sdk_upgrade_package_t* package); }
extern "C" { uint32_t (__cdecl *tobii_sdk_upgrade_package_get_num_parts)( const tobii_sdk_upgrade_package_t* package, tobii_sdk_error_t** error); }
extern "C" { tobii_sdk_upgrade_package_part_t* (__cdecl *tobii_sdk_upgrade_package_get_part)( tobii_sdk_upgrade_package_t* package, uint32_t index, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_upgrade_package_append_part)( tobii_sdk_upgrade_package_t* package, tobii_sdk_upgrade_package_part_t* part, tobii_sdk_error_t** error); }
extern "C" { tobii_sdk_upgrade_package_finalized_t* (__cdecl *tobii_sdk_upgrade_package_finalize)( tobii_sdk_upgrade_package_t* package, tobii_sdk_error_t** error); }
extern "C" { const uint8_t* (__cdecl *tobii_sdk_upgrade_package_finalized_get_data)( const tobii_sdk_upgrade_package_finalized_t* finalized, tobii_sdk_error_t** error); }
extern "C" { uint32_t (__cdecl *tobii_sdk_upgrade_package_finalized_get_size)( const tobii_sdk_upgrade_package_finalized_t* finalized, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_upgrade_package_finalized_destroy)( tobii_sdk_upgrade_package_finalized_t* finalized); }
extern "C" { tobii_sdk_upgrade_package_part_t* (__cdecl *tobii_sdk_upgrade_package_part_create_raw_part)( uint32_t type, uint32_t flags, uint32_t size, uint32_t id, uint32_t order, const uint8_t* payload, tobii_sdk_error_t** error); }
extern "C" { tobii_sdk_upgrade_package_part_t* (__cdecl *tobii_sdk_upgrade_package_part_create_legacy_metadata_part)( uint32_t flags, uint32_t id, uint32_t order, const char* key, const char* value, tobii_sdk_error_t** error); }
extern "C" { tobii_sdk_upgrade_package_part_t* (__cdecl *tobii_sdk_upgrade_package_part_create_legacy_file_part)( uint32_t flags, uint32_t id, uint32_t order, const char* target_path, const uint8_t* file_contents, uint32_t file_size, tobii_sdk_error_t** error); }
extern "C" { tobii_sdk_upgrade_package_part_t* (__cdecl *tobii_sdk_upgrade_package_part_create_legacy_exec_command_part)( uint32_t flags, uint32_t id, uint32_t order, uint32_t exec_flags, const char* command_line, tobii_sdk_error_t** error); }
extern "C" { tobii_sdk_upgrade_package_part_t* (__cdecl *tobii_sdk_upgrade_package_part_create_cancancel_part)( uint32_t flags, uint32_t id, uint32_t order, uint32_t cancancel, tobii_sdk_error_t** error); }
extern "C" { const char* (__cdecl *tobii_sdk_upgrade_package_part_get_representation)( const tobii_sdk_upgrade_package_part_t* part, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_upgrade_package_part_destroy)( tobii_sdk_upgrade_package_part_t* part); }
extern "C" { tobii_sdk_upgrade_progress_reporter_t* (__cdecl *tobii_sdk_upgrade_progress_reporter_create)( tobii_sdk_upgrade_completed_handler_t completion_handler, tobii_sdk_upgrade_progress_handler_t progress_handler, tobii_sdk_upgrade_cancancel_changed_handler_t cancancel_handler, void* user_data, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_upgrade_progress_reporter_get_progress)( tobii_sdk_upgrade_progress_reporter_t* progress_reporter, uint32_t* current_step, uint32_t* number_of_steps, uint32_t* percent, tobii_sdk_error_t** error); }
extern "C" { uint32_t (__cdecl *tobii_sdk_upgrade_progress_get_can_cancel)( tobii_sdk_upgrade_progress_reporter_t* progress_reporter, tobii_sdk_error_t** error); }
extern "C" { uint32_t (__cdecl *tobii_sdk_upgrade_progress_cancel)( tobii_sdk_upgrade_progress_reporter_t* progress_reporter, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_upgrade_progress_reporter_destroy)( tobii_sdk_upgrade_progress_reporter_t* progress_reporter); }
extern "C" { uint32_t (__cdecl *tobii_sdk_upgrade_package_is_compatible_with_device)( tobii_sdk_mainloop_t* mainloop, const tobii_sdk_upgrade_package_t* package, const tobii_sdk_device_info_t* device, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_upgrade_begin)( tobii_sdk_mainloop_t* mainloop, const tobii_sdk_upgrade_package_t* package, const tobii_sdk_device_info_t* device, tobii_sdk_upgrade_progress_reporter_t* progress_reporter, tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_init)( tobii_sdk_error_t** error); }
extern "C" { void (__cdecl *tobii_sdk_free_string)( const char* str); }
extern "C" { tobii_sdk_blob_t* (__cdecl *tobii_sdk_hmac_perform)( uint32_t algorithm, const char* key, uint32_t key_length, const char* input, uint32_t input_length, tobii_sdk_error_t** error); }


static const Dylib::Import imports[] =
{
  { "tobii_sdk_error_destroy", (void**)&tobii_sdk_error_destroy, Dylib::Import::cMangled },
  { "tobii_sdk_error_clone", (void**)&tobii_sdk_error_clone, Dylib::Import::cMangled },
  { "tobii_sdk_error_get_message", (void**)&tobii_sdk_error_get_message, Dylib::Import::cMangled },
  { "tobii_sdk_error_get_code", (void**)&tobii_sdk_error_get_code, Dylib::Import::cMangled },
  { "tobii_sdk_error_to_string", (void**)&tobii_sdk_error_to_string, Dylib::Import::cMangled },
  { "tobii_sdk_error_is_failure", (void**)&tobii_sdk_error_is_failure, Dylib::Import::cMangled },
  { "tobii_sdk_error_convert_code_to_string", (void**)&tobii_sdk_error_convert_code_to_string, Dylib::Import::cMangled },
  { "tobii_sdk_error_create_generic", (void**)&tobii_sdk_error_create_generic, Dylib::Import::cMangled },
  { "tobii_sdk_blob_create", (void**)&tobii_sdk_blob_create, Dylib::Import::cMangled },
  { "tobii_sdk_blob_get_size", (void**)&tobii_sdk_blob_get_size, Dylib::Import::cMangled },
  { "tobii_sdk_blob_get_data", (void**)&tobii_sdk_blob_get_data, Dylib::Import::cMangled },
  { "tobii_sdk_blob_destroy", (void**)&tobii_sdk_blob_destroy, Dylib::Import::cMangled },
  { "tobii_sdk_mainloop_create", (void**)&tobii_sdk_mainloop_create, Dylib::Import::cMangled },
  { "tobii_sdk_mainloop_run", (void**)&tobii_sdk_mainloop_run, Dylib::Import::cMangled },
  { "tobii_sdk_mainloop_quit", (void**)&tobii_sdk_mainloop_quit, Dylib::Import::cMangled },
  { "tobii_sdk_mainloop_destroy", (void**)&tobii_sdk_mainloop_destroy, Dylib::Import::cMangled },
  { "tobii_sdk_device_info_iterator_move_next", (void**)&tobii_sdk_device_info_iterator_move_next, Dylib::Import::cMangled },
  { "tobii_sdk_device_info_iterator_get_key_name", (void**)&tobii_sdk_device_info_iterator_get_key_name, Dylib::Import::cMangled },
  { "tobii_sdk_device_info_iterator_destroy", (void**)&tobii_sdk_device_info_iterator_destroy, Dylib::Import::cMangled },
  { "tobii_sdk_device_info_clone", (void**)&tobii_sdk_device_info_clone, Dylib::Import::cMangled },
  { "tobii_sdk_device_info_create_test", (void**)&tobii_sdk_device_info_create_test, Dylib::Import::cMangled },
  { "tobii_sdk_device_info_get_product_id", (void**)&tobii_sdk_device_info_get_product_id, Dylib::Import::cMangled },
  { "tobii_sdk_device_info_get", (void**)&tobii_sdk_device_info_get, Dylib::Import::cMangled },
  { "tobii_sdk_device_info_get_iterator", (void**)&tobii_sdk_device_info_get_iterator, Dylib::Import::cMangled },
  { "tobii_sdk_device_info_get_factory_info", (void**)&tobii_sdk_device_info_get_factory_info, Dylib::Import::cMangled },
  { "tobii_sdk_device_info_destroy", (void**)&tobii_sdk_device_info_destroy, Dylib::Import::cMangled },
  { "tobii_sdk_factory_info_create_for_networked_eyetracker", (void**)&tobii_sdk_factory_info_create_for_networked_eyetracker, Dylib::Import::cMangled },
  { "tobii_sdk_factory_info_get_representation", (void**)&tobii_sdk_factory_info_get_representation, Dylib::Import::cMangled },
  { "tobii_sdk_factory_info_destroy", (void**)&tobii_sdk_factory_info_destroy, Dylib::Import::cMangled },
  { "tobii_sdk_device_browser_create", (void**)&tobii_sdk_device_browser_create, Dylib::Import::cMangled },
  { "tobii_sdk_device_browser_destroy", (void**)&tobii_sdk_device_browser_destroy, Dylib::Import::cMangled },
  { "tobii_sdk_device_browser_get_device_list", (void**)&tobii_sdk_device_browser_get_device_list, Dylib::Import::cMangled },
  { "tobii_sdk_device_info_list_get_size", (void**)&tobii_sdk_device_info_list_get_size, Dylib::Import::cMangled },
  { "tobii_sdk_device_info_list_get_at_index", (void**)&tobii_sdk_device_info_list_get_at_index, Dylib::Import::cMangled },
  { "tobii_sdk_device_info_list_destroy", (void**)&tobii_sdk_device_info_list_destroy, Dylib::Import::cMangled },
  { "tobii_sdk_vector_type_is_compatible", (void**)&tobii_sdk_vector_type_is_compatible, Dylib::Import::cMangled },
  { "tobii_sdk_vector_create", (void**)&tobii_sdk_vector_create, Dylib::Import::cMangled },
  { "tobii_sdk_vector_destroy", (void**)&tobii_sdk_vector_destroy, Dylib::Import::cMangled },
  { "tobii_sdk_vector_get_element_type", (void**)&tobii_sdk_vector_get_element_type, Dylib::Import::cMangled },
  { "tobii_sdk_vector_get_length", (void**)&tobii_sdk_vector_get_length, Dylib::Import::cMangled },
  { "tobii_sdk_vector_get_int32", (void**)&tobii_sdk_vector_get_int32, Dylib::Import::cMangled },
  { "tobii_sdk_vector_get_uint32", (void**)&tobii_sdk_vector_get_uint32, Dylib::Import::cMangled },
  { "tobii_sdk_vector_get_fixed_15x16_as_float32", (void**)&tobii_sdk_vector_get_fixed_15x16_as_float32, Dylib::Import::cMangled },
  { "tobii_sdk_vector_get_fixed_22x41_as_float64", (void**)&tobii_sdk_vector_get_fixed_22x41_as_float64, Dylib::Import::cMangled },
  { "tobii_sdk_vector_get_string", (void**)&tobii_sdk_vector_get_string, Dylib::Import::cMangled },
  { "tobii_sdk_vector_get_string_length", (void**)&tobii_sdk_vector_get_string_length, Dylib::Import::cMangled },
  { "tobii_sdk_vector_set_int32", (void**)&tobii_sdk_vector_set_int32, Dylib::Import::cMangled },
  { "tobii_sdk_vector_set_uint32", (void**)&tobii_sdk_vector_set_uint32, Dylib::Import::cMangled },
  { "tobii_sdk_vector_set_fixed_15x16_as_float32", (void**)&tobii_sdk_vector_set_fixed_15x16_as_float32, Dylib::Import::cMangled },
  { "tobii_sdk_vector_set_fixed_22x41_as_float64", (void**)&tobii_sdk_vector_set_fixed_22x41_as_float64, Dylib::Import::cMangled },
  { "tobii_sdk_vector_set_string", (void**)&tobii_sdk_vector_set_string, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_create", (void**)&tobii_sdk_param_stack_create, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_create_test_stack", (void**)&tobii_sdk_param_stack_create_test_stack, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_clone", (void**)&tobii_sdk_param_stack_clone, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_destroy", (void**)&tobii_sdk_param_stack_destroy, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_get_size", (void**)&tobii_sdk_param_stack_get_size, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_get_type", (void**)&tobii_sdk_param_stack_get_type, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_append", (void**)&tobii_sdk_param_stack_append, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_get_int32", (void**)&tobii_sdk_param_stack_get_int32, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_get_uint32", (void**)&tobii_sdk_param_stack_get_uint32, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_get_int64", (void**)&tobii_sdk_param_stack_get_int64, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_get_uint64", (void**)&tobii_sdk_param_stack_get_uint64, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_get_float32", (void**)&tobii_sdk_param_stack_get_float32, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_get_float64", (void**)&tobii_sdk_param_stack_get_float64, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_get_fixed_15x16_as_float32", (void**)&tobii_sdk_param_stack_get_fixed_15x16_as_float32, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_get_fixed_22x41_as_float64", (void**)&tobii_sdk_param_stack_get_fixed_22x41_as_float64, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_get_node_prolog", (void**)&tobii_sdk_param_stack_get_node_prolog, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_get_string", (void**)&tobii_sdk_param_stack_get_string, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_get_string_length", (void**)&tobii_sdk_param_stack_get_string_length, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_get_blob_length", (void**)&tobii_sdk_param_stack_get_blob_length, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_get_vector", (void**)&tobii_sdk_param_stack_get_vector, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_push_int32", (void**)&tobii_sdk_param_stack_push_int32, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_push_uint32", (void**)&tobii_sdk_param_stack_push_uint32, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_push_int64", (void**)&tobii_sdk_param_stack_push_int64, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_push_uint64", (void**)&tobii_sdk_param_stack_push_uint64, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_push_string", (void**)&tobii_sdk_param_stack_push_string, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_push_float32_as_fixed_15x16", (void**)&tobii_sdk_param_stack_push_float32_as_fixed_15x16, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_push_float64_as_fixed_22x41", (void**)&tobii_sdk_param_stack_push_float64_as_fixed_22x41, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_push_node_prolog", (void**)&tobii_sdk_param_stack_push_node_prolog, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_push_float32", (void**)&tobii_sdk_param_stack_push_float32, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_push_float64", (void**)&tobii_sdk_param_stack_push_float64, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_push_blob", (void**)&tobii_sdk_param_stack_push_blob, Dylib::Import::cMangled },
  { "tobii_sdk_param_stack_push_vector", (void**)&tobii_sdk_param_stack_push_vector, Dylib::Import::cMangled },
  { "tobii_sdk_callback_connection_destroy", (void**)&tobii_sdk_callback_connection_destroy, Dylib::Import::cMangled },
  { "tobii_sdk_message_passer_get", (void**)&tobii_sdk_message_passer_get, Dylib::Import::cMangled },
  { "tobii_sdk_message_passer_destroy", (void**)&tobii_sdk_message_passer_destroy, Dylib::Import::cMangled },
  { "tobii_sdk_message_passer_enable_nop_sending", (void**)&tobii_sdk_message_passer_enable_nop_sending, Dylib::Import::cMangled },
  { "tobii_sdk_message_passer_disable_nop_sending", (void**)&tobii_sdk_message_passer_disable_nop_sending, Dylib::Import::cMangled },
  { "tobii_sdk_message_passer_execute_request", (void**)&tobii_sdk_message_passer_execute_request, Dylib::Import::cMangled },
  { "tobii_sdk_message_passer_add_data_handler", (void**)&tobii_sdk_message_passer_add_data_handler, Dylib::Import::cMangled },
  { "tobii_sdk_message_passer_add_error_handler", (void**)&tobii_sdk_message_passer_add_error_handler, Dylib::Import::cMangled },
  { "tobii_sdk_clock_get_default", (void**)&tobii_sdk_clock_get_default, Dylib::Import::cMangled },
  { "tobii_sdk_clock_create_user_defined", (void**)&tobii_sdk_clock_create_user_defined, Dylib::Import::cMangled },
  { "tobii_sdk_clock_get_time", (void**)&tobii_sdk_clock_get_time, Dylib::Import::cMangled },
  { "tobii_sdk_clock_get_resolution", (void**)&tobii_sdk_clock_get_resolution, Dylib::Import::cMangled },
  { "tobii_sdk_clock_destroy", (void**)&tobii_sdk_clock_destroy, Dylib::Import::cMangled },
  { "tobii_sdk_sync_state_clone", (void**)&tobii_sdk_sync_state_clone, Dylib::Import::cMangled },
  { "tobii_sdk_sync_state_destroy", (void**)&tobii_sdk_sync_state_destroy, Dylib::Import::cMangled },
  { "tobii_sdk_sync_state_get_sync_state_flag", (void**)&tobii_sdk_sync_state_get_sync_state_flag, Dylib::Import::cMangled },
  { "tobii_sdk_sync_state_get_number_of_points_in_use", (void**)&tobii_sdk_sync_state_get_number_of_points_in_use, Dylib::Import::cMangled },
  { "tobii_sdk_sync_state_get_point_in_use", (void**)&tobii_sdk_sync_state_get_point_in_use, Dylib::Import::cMangled },
  { "tobii_sdk_sync_state_get_error_approximation", (void**)&tobii_sdk_sync_state_get_error_approximation, Dylib::Import::cMangled },
  { "tobii_sdk_sync_manager_create", (void**)&tobii_sdk_sync_manager_create, Dylib::Import::cMangled },
  { "tobii_sdk_sync_manager_convert_from_local_to_remote", (void**)&tobii_sdk_sync_manager_convert_from_local_to_remote, Dylib::Import::cMangled },
  { "tobii_sdk_sync_manager_convert_from_remote_to_local", (void**)&tobii_sdk_sync_manager_convert_from_remote_to_local, Dylib::Import::cMangled },
  { "tobii_sdk_sync_manager_get_sync_state", (void**)&tobii_sdk_sync_manager_get_sync_state, Dylib::Import::cMangled },
  { "tobii_sdk_sync_manager_destroy", (void**)&tobii_sdk_sync_manager_destroy, Dylib::Import::cMangled },
  { "tobii_sdk_upgrade_package_create", (void**)&tobii_sdk_upgrade_package_create, Dylib::Import::cMangled },
  { "tobii_sdk_upgrade_package_parse", (void**)&tobii_sdk_upgrade_package_parse, Dylib::Import::cMangled },
  { "tobii_sdk_upgrade_package_destroy", (void**)&tobii_sdk_upgrade_package_destroy, Dylib::Import::cMangled },
  { "tobii_sdk_upgrade_package_get_num_parts", (void**)&tobii_sdk_upgrade_package_get_num_parts, Dylib::Import::cMangled },
  { "tobii_sdk_upgrade_package_get_part", (void**)&tobii_sdk_upgrade_package_get_part, Dylib::Import::cMangled },
  { "tobii_sdk_upgrade_package_append_part", (void**)&tobii_sdk_upgrade_package_append_part, Dylib::Import::cMangled },
  { "tobii_sdk_upgrade_package_finalize", (void**)&tobii_sdk_upgrade_package_finalize, Dylib::Import::cMangled },
  { "tobii_sdk_upgrade_package_finalized_get_data", (void**)&tobii_sdk_upgrade_package_finalized_get_data, Dylib::Import::cMangled },
  { "tobii_sdk_upgrade_package_finalized_get_size", (void**)&tobii_sdk_upgrade_package_finalized_get_size, Dylib::Import::cMangled },
  { "tobii_sdk_upgrade_package_finalized_destroy", (void**)&tobii_sdk_upgrade_package_finalized_destroy, Dylib::Import::cMangled },
  { "tobii_sdk_upgrade_package_part_create_raw_part", (void**)&tobii_sdk_upgrade_package_part_create_raw_part, Dylib::Import::cMangled },
  { "tobii_sdk_upgrade_package_part_create_legacy_metadata_part", (void**)&tobii_sdk_upgrade_package_part_create_legacy_metadata_part, Dylib::Import::cMangled },
  { "tobii_sdk_upgrade_package_part_create_legacy_file_part", (void**)&tobii_sdk_upgrade_package_part_create_legacy_file_part, Dylib::Import::cMangled },
  { "tobii_sdk_upgrade_package_part_create_legacy_exec_command_part", (void**)&tobii_sdk_upgrade_package_part_create_legacy_exec_command_part, Dylib::Import::cMangled },
  { "tobii_sdk_upgrade_package_part_create_cancancel_part", (void**)&tobii_sdk_upgrade_package_part_create_cancancel_part, Dylib::Import::cMangled },
  { "tobii_sdk_upgrade_package_part_get_representation", (void**)&tobii_sdk_upgrade_package_part_get_representation, Dylib::Import::cMangled },
  { "tobii_sdk_upgrade_package_part_destroy", (void**)&tobii_sdk_upgrade_package_part_destroy, Dylib::Import::cMangled },
  { "tobii_sdk_upgrade_progress_reporter_create", (void**)&tobii_sdk_upgrade_progress_reporter_create, Dylib::Import::cMangled },
  { "tobii_sdk_upgrade_progress_reporter_get_progress", (void**)&tobii_sdk_upgrade_progress_reporter_get_progress, Dylib::Import::cMangled },
  { "tobii_sdk_upgrade_progress_get_can_cancel", (void**)&tobii_sdk_upgrade_progress_get_can_cancel, Dylib::Import::cMangled },
  { "tobii_sdk_upgrade_progress_cancel", (void**)&tobii_sdk_upgrade_progress_cancel, Dylib::Import::cMangled },
  { "tobii_sdk_upgrade_progress_reporter_destroy", (void**)&tobii_sdk_upgrade_progress_reporter_destroy, Dylib::Import::cMangled },
  { "tobii_sdk_upgrade_package_is_compatible_with_device", (void**)&tobii_sdk_upgrade_package_is_compatible_with_device, Dylib::Import::cMangled },
  { "tobii_sdk_upgrade_begin", (void**)&tobii_sdk_upgrade_begin, Dylib::Import::cMangled },
  { "tobii_sdk_init", (void**)&tobii_sdk_init, Dylib::Import::cMangled },
  { "tobii_sdk_free_string", (void**)&tobii_sdk_free_string, Dylib::Import::cMangled },
  { "tobii_sdk_hmac_perform", (void**)&tobii_sdk_hmac_perform, Dylib::Import::cMangled },
  { 0, 0, 0 }
};

// Here you may specify a custom error message to be displayed when the library cannot be found.
static const char* notFoundMsg = "";
// Here you may specify an URL to some local or remote help resource.
static const char* notFoundURL = "";
RegisterDylib( tetio, imports, notFoundMsg, notFoundURL );
