// Import declarations for BioRadio150DLL.h, generated by dylib_imports.sh
#ifndef BioRadio150DLL_IMPORTS_H
#define BioRadio150DLL_IMPORTS_H

#include "Win32Defs.h"

#define FindDevices FindDevices_e728
#define FindDevicesSimple FindDevicesSimple_7e5d
#define CreateBioRadio CreateBioRadio_ab41
#define DestroyBioRadio DestroyBioRadio_b19f
#define StartCommunication StartCommunication_2d25
#define StartAcq StartAcq_d043
#define StopAcq StopAcq_40fa
#define DisableBuffering DisableBuffering_c752
#define EnableBuffering EnableBuffering_0516
#define StopCommunication StopCommunication_46bf
#define LoadConfig LoadConfig_6177
#define SaveConfig SaveConfig_843a
#define PingConfig PingConfig_b249
#define GetConfig GetConfig_99c7
#define ProgramConfig ProgramConfig_1dc7
#define SetConfig SetConfig_40c0
#define GetSampleRate GetSampleRate_c9ca
#define GetBitResolution GetBitResolution_a457
#define GetFastSweepsPerPacket GetFastSweepsPerPacket_82b1
#define GetSlowSweepsPerPacket GetSlowSweepsPerPacket_fcb3
#define GetNumEnabledInputs GetNumEnabledInputs_516b
#define GetNumEnabledSlowInputs GetNumEnabledSlowInputs_6ee4
#define GetNumEnabledFastInputs GetNumEnabledFastInputs_9b1a
#define GetMode GetMode_e701
#define GetNumChannels GetNumChannels_55c4
#define GetEnabledFastInputs GetEnabledFastInputs_e7b6
#define GetEnabledSlowInputs GetEnabledSlowInputs_e0ed
#define TransferBuffer TransferBuffer_ba80
#define ReadScaledData ReadScaledData_3bc5
#define ReadRawData ReadRawData_5429
#define ReadScaledFastAndSlowData ReadScaledFastAndSlowData_bbe2
#define ReadRawFastAndSlowData ReadRawFastAndSlowData_11da
#define SetBadDataValues SetBadDataValues_7bdf
#define SetPadWait SetPadWait_65c8
#define GetRFChannel GetRFChannel_8370
#define SetRFChannel SetRFChannel_2d68
#define GetUsableRFChannelList GetUsableRFChannelList_d86f
#define GetFreqHoppingMode GetFreqHoppingMode_285d
#define GetFreqHoppingModeIndicator GetFreqHoppingModeIndicator_77e0
#define SetFreqHoppingMode SetFreqHoppingMode_2279
#define GetGoodPackets GetGoodPackets_770b
#define GetBadPackets GetBadPackets_56e3
#define GetDroppedPackets GetDroppedPackets_d3b1
#define GetUpRSSI GetUpRSSI_0b95
#define GetDownRSSI GetDownRSSI_954d
#define GetLinkBufferSize GetLinkBufferSize_ae11
#define GetBitErrCount GetBitErrCount_d227
#define GetBitErrRate GetBitErrRate_553c
#define GetBatteryStatus GetBatteryStatus_e4f3
#define GetBioRadioModelString GetBioRadioModelString_71f0
#define GetDeviceID GetDeviceID_af1b
#define GetDeviceIDString GetDeviceIDString_e405
#define GetFirmwareVersionString GetFirmwareVersionString_6b2a
#define GetDLLVersionString GetDLLVersionString_06cf

#include "BioRadio150DLL.h"

#undef FindDevices
#undef FindDevicesSimple
#undef CreateBioRadio
#undef DestroyBioRadio
#undef StartCommunication
#undef StartAcq
#undef StopAcq
#undef DisableBuffering
#undef EnableBuffering
#undef StopCommunication
#undef LoadConfig
#undef SaveConfig
#undef PingConfig
#undef GetConfig
#undef ProgramConfig
#undef SetConfig
#undef GetSampleRate
#undef GetBitResolution
#undef GetFastSweepsPerPacket
#undef GetSlowSweepsPerPacket
#undef GetNumEnabledInputs
#undef GetNumEnabledSlowInputs
#undef GetNumEnabledFastInputs
#undef GetMode
#undef GetNumChannels
#undef GetEnabledFastInputs
#undef GetEnabledSlowInputs
#undef TransferBuffer
#undef ReadScaledData
#undef ReadRawData
#undef ReadScaledFastAndSlowData
#undef ReadRawFastAndSlowData
#undef SetBadDataValues
#undef SetPadWait
#undef GetRFChannel
#undef SetRFChannel
#undef GetUsableRFChannelList
#undef GetFreqHoppingMode
#undef GetFreqHoppingModeIndicator
#undef SetFreqHoppingMode
#undef GetGoodPackets
#undef GetBadPackets
#undef GetDroppedPackets
#undef GetUpRSSI
#undef GetDownRSSI
#undef GetLinkBufferSize
#undef GetBitErrCount
#undef GetBitErrRate
#undef GetBatteryStatus
#undef GetBioRadioModelString
#undef GetDeviceID
#undef GetDeviceIDString
#undef GetFirmwareVersionString
#undef GetDLLVersionString

extern "C" {
extern BOOL (__stdcall *FindDevices)(TDeviceInfo *DeviceList, int *DeviceCount, int MaxCount, TUpdateStatusEvent UpdateStatusProc);
extern BOOL (__stdcall *FindDevicesSimple)(char *DevicePortNameList[], int *DeviceCount, int MaxDeviceCount, int PortNameStrLen);
extern unsigned int (__stdcall *CreateBioRadio)();
extern int (__stdcall *DestroyBioRadio)(unsigned int BioRadio150);
extern int (__stdcall *StartCommunication)(unsigned int BioRadio150 , char *PortName);
extern int (__stdcall *StartAcq)(unsigned int BioRadio150, char DisplayProgressDialog);
extern int (__stdcall *StopAcq)(unsigned int BioRadio150);
extern int (__stdcall *DisableBuffering)(unsigned int BioRadio150);
extern int (__stdcall *EnableBuffering)(unsigned int BioRadio150);
extern int (__stdcall *StopCommunication)(unsigned int BioRadio150);
extern int (__stdcall *LoadConfig)(unsigned int BioRadio150, char *Filename);
extern int (__stdcall *SaveConfig)(unsigned int BioRadio150, char *Filename);
extern int (__stdcall *PingConfig)(unsigned int BioRadio150, char DisplayProgressDialog);
extern int (__stdcall *GetConfig)(unsigned int BioRadio150, TBioRadioConfig *ConfigStruct, char PingDevice, char DisplayProgressDialog);
extern int (__stdcall *ProgramConfig)(unsigned int BioRadio150, char DisplayProgressDialog, const char *Filename);
extern int (__stdcall *SetConfig)(unsigned int BioRadio150, TBioRadioConfig *ConfigStruct, char ProgramDevice, char DisplayProgressDialog);
extern long (__stdcall *GetSampleRate)(unsigned int BioRadio150);
extern long (__stdcall *GetBitResolution)(unsigned int BioRadio150);
extern int (__stdcall *GetFastSweepsPerPacket)(unsigned int BioRadio150);
extern int (__stdcall *GetSlowSweepsPerPacket)(unsigned int BioRadio150);
extern int (__stdcall *GetNumEnabledInputs)(unsigned int BioRadio150, int *FastMainInputs, int *FastAuxInputs, int *SlowAuxInputs);
extern int (__stdcall *GetNumEnabledSlowInputs)(unsigned int BioRadio150);
extern int (__stdcall *GetNumEnabledFastInputs)(unsigned int BioRadio150);
extern long (__stdcall *GetMode)(unsigned int BioRadio150, WORD &Mode);
extern long (__stdcall *GetNumChannels)(unsigned int BioRadio150);
extern WORD (__stdcall *GetEnabledFastInputs)(unsigned int BioRadio150);
extern char (__stdcall *GetEnabledSlowInputs)(unsigned int BioRadio150);
extern int (__stdcall *TransferBuffer)(unsigned int BioRadio150);
extern int (__stdcall *ReadScaledData)(unsigned int BioRadio150, double *Data, int Size, int *NumRead);
extern int (__stdcall *ReadRawData)(unsigned int BioRadio150, WORD *Data, int Size, int *NumRead);
extern int (__stdcall *ReadScaledFastAndSlowData)(unsigned int BioRadio150, double *FastInputsData, int FastInputsSize, int *FastInputsNumRead, WORD *SlowInputsData, int SlowInputsSize, int *SlowInputsNumRead);
extern int (__stdcall *ReadRawFastAndSlowData)(unsigned int BioRadio150, WORD *FastInputsData, int FastInputsSize, int *FastInputsNumRead, WORD *SlowInputsData, int SlowInputsSize, int *SlowInputsNumRead);
extern int (__stdcall *SetBadDataValues)(unsigned int BioRadio150, double BadDataValueScaled, WORD BadDataValueRaw);
extern int (__stdcall *SetPadWait)(unsigned int BioRadio150, int numMissingPackets);
extern int (__stdcall *GetRFChannel)(unsigned int BioRadio150);
extern int (__stdcall *SetRFChannel)(unsigned int BioRadio150, int RFChannel);
extern int (__stdcall *GetUsableRFChannelList)(int *UsableRFChannelList, int Size);
extern int (__stdcall *GetFreqHoppingMode)(unsigned int BioRadio150);
extern int (__stdcall *GetFreqHoppingModeIndicator)();
extern int (__stdcall *SetFreqHoppingMode)(unsigned int BioRadio150, bool HoppingEnabled);
extern unsigned int (__stdcall *GetGoodPackets)(unsigned int BioRadio150);
extern unsigned int (__stdcall *GetBadPackets)(unsigned int BioRadio150);
extern unsigned int (__stdcall *GetDroppedPackets)(unsigned int BioRadio150);
extern int (__stdcall *GetUpRSSI)(unsigned int BioRadio150);
extern int (__stdcall *GetDownRSSI)(unsigned int BioRadio150);
extern int (__stdcall *GetLinkBufferSize)(unsigned int BioRadio150);
extern int (__stdcall *GetBitErrCount)(unsigned int BioRadio150);
extern int (__stdcall *GetBitErrRate)(unsigned int BioRadio150);
extern double (__stdcall *GetBatteryStatus)(unsigned int BioRadio150);
extern int (__stdcall *GetBioRadioModelString)(unsigned int BioRadio150, char *BioRadioModelString, int StrLength);
extern int (__stdcall *GetDeviceID)(unsigned int BioRadio150, WORD *DeviceID);
extern int (__stdcall *GetDeviceIDString)(unsigned int BioRadio150, char *DeviceIDCStr, int StrLength);
extern int (__stdcall *GetFirmwareVersionString)(unsigned int BioRadio150, char *VersionString, int StrLength);
extern void (__stdcall *GetDLLVersionString)(char *VersionString, int StrLength);
}

namespace Dylib { bool BioRadio150DLL_Loaded(); }

#endif // BioRadio150DLL_IMPORTS_H
